### ISSUE TITLE
Should we add more about using roostock?

### ISSUE THREAD

**Issue by slochower** [greenelab/meta-review#104]
For context: https://github.com/greenelab/meta-review/pull/99#discussion_r224185103

**Comment by agitter** [comment]
To continue this discussion, we currently say:
> An [example repository](https://github.com/greenelab/manubot-rootstock) demonstrates Manubot’s features and serves as a template for users to write their own manuscript with Manubot.

We also have elsewhere
> The process of writing and revising material can be orchestrated through GitHub with a web browser or a local text editor.

I don't think we can claim that the rootstock makes it easy to start a new manuscript with Manubot.  it simplifies the processes considerably but requires some technical expertise and has been a failure point for new users.

Do we want to bring the two sentences closer together to make the point that once a manuscript has been created from the rootstock it can be easy for collaborators to edit the markdown and contribute?

**Comment by slochower** [comment]
I think hold off on this text for now so we can prioritize resubmitting in the near future.

**Comment by agitter** [comment]
Sounds good to me.  I'll leave the issue open for discussion later but prioritize submitting what we have.
