### ISSUE TITLE
introductory paragraph needs more citations.

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#114]
as is, the introductory paragraph is missing citations for statements.

in particular, the statement "However, the scientific community requires tools whose workflows encourage openness" should either have a citation or two, or be clarified as an opinion.

**Comment by agitter** [comment]
@dhimmel do you know of references we should use here?  If not, I'll help look for them.

**Comment by dhimmel** [comment]
@agitter I forgot to update response-to-reviewers. Can you take a look at https://github.com/dhimmel/meta-review/commit/7e489f99e7a2e1ad76886bab78f3b4c2f672a80f?
