### ISSUE TITLE
"We use GitHub issues for organization"

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#118]
is there anything special about how manubot links to and from issues in the text? mostly just curious. (I could imagine automatically generated backreferences, as github does between issues when you mention one issue in another issue).

**Comment by dhimmel** [comment]
For general reference, GitHub [autolinked](https://help.github.com/en/articles/autolinked-references-and-urls) certain references and URLs to other GitHub pages. For example, here is raw text:

```
https://github.com/greenelab/meta-review/commit/d4a642efa06896209ddfa6e3d2387a58232e61f5
d4a642efa06896209ddfa6e3d2387a58232e61f5
https://github.com/greenelab/meta-review/issues/118
https://github.com/greenelab/meta-review/issues/118#issue-406904570
 ```

The following text is pasted below, and will display with GitHub's shortened link syntax:

https://github.com/greenelab/meta-review/commit/d4a642efa06896209ddfa6e3d2387a58232e61f5
d4a642efa06896209ddfa6e3d2387a58232e61f5
https://github.com/greenelab/meta-review/issues/118
https://github.com/greenelab/meta-review/issues/118#issue-406904570

Manubot does not do any special interpretation of in-text links to GitHub. We could potentially write a `pandoc-filter` to perform similar functionality as above, but it is not a high priority. 

> I could imagine automatically generated backreferences

Backreferences that appear in GitHub issues / pull requests are entirely up to the discretion of GitHub. I think it's unlikely they will show backreferences to issues/PRs from other webpages or in code files anytime soon.
