### ISSUE TITLE
further emphasize strikethrough formatting for errors in extant versions

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#122]
I love the paragraph on Sci-Hub error correction - am I correct in understanding that the link to the erroneous version of the pub was updated with a version that clearly highlighted the text as erroneous? this is really important if so, and has massive implications for the future of scholarly docs!

(and, out of curiousity, how do you do this with links that have a hash in them, or did I misunderstand? I can investigate this myself once I have a better network connection)

**Comment by dhimmel** [comment]
Quoting the relevant [manuscript](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/) section:

> Since its creation to facilitate the Deep Review, Manubot has been used to write a variety of scholarly documents. The [Sci-Hub Coverage Study](https://github.com/greenelab/scihub-manuscript) — performed openly on GitHub from its inception — investigated Sci-Hub’s repository of pirated articles [[34](https://greenelab.github.io/meta-review/v/ae1dd9ebd7b533b578041fd402217a73fd113899/#ref-IhliSZDo)]. Sci-Hub [reviewed](https://github.com/greenelab/scihub-manuscript/issues/17) the initial preprint from this study in a series of tweets, pointing out a major error in one of the analyses. Within hours, the authors used Markdown’s strikethrough formatting in Manubot to cross-out the errant sentences ([commit](https://github.com/greenelab/scihub-manuscript/commit/8fcd0cd665f6fb5f39bed7e26b940aa27d4770ba), [versioned manuscript](https://greenelab.github.io/scihub-manuscript/v/8fcd0cd665f6fb5f39bed7e26b940aa27d4770ba/)), thereby alerting readers to the mistake and preventing further propagation of misinformation. One month later, a larger [set of revisions](https://github.com/greenelab/scihub-manuscript/pull/19)explained the error in more detail and was included in a second version of the preprint. As such, continuous publishing via Manubot helped the authors address the error without delay, while retaining a public version history of the process.

@ctb the strikethrough formatting is not retroactive. None of the manuscript versions prior to the [commit](https://github.com/greenelab/scihub-manuscript/commit/8fcd0cd665f6fb5f39bed7e26b940aa27d4770ba) with the strikethrough changed. However, once the commit was deployed via GitHub Pages in https://github.com/greenelab/scihub-manuscript/commit/b3db283dfc08b2a46a894446fda016bfbc41baf6, the latest version of the manuscript immediately showed the strikethrough as [shown here](https://greenelab.github.io/scihub-manuscript/v/8fcd0cd665f6fb5f39bed7e26b940aa27d4770ba/#sci-hub-request-logs):

> ![image](https://user-images.githubusercontent.com/1117703/52299002-629ca180-2952-11e9-99b8-16091675d52a.png)

It would be possible to manually edit the HTML of the past versions on the `gh-pages` branch to add the strikethrough. However, this is not something we recommend, as we think it's of utmost importance that the permalinks continue to refer to the same manuscript. Editing versioned `manuscript.html` files on `gh-pages` would also mean that the commit hash used as the version is no longer fully sufficient to create that output. On the other hand, the record of how this happened would be preserved and accessible, so perhaps it could be justifiable in some situations.

Should one need to alert viewers of past versions to critical mistakes, I'd recommend leaving Hypothesis annotations / highlights.

> am I correct in understanding that the link to the erroneous version of the pub was updated with a version that clearly highlighted the text as erroneous?

It should be clear, but the the manuscripts at versioned links did not change. However, the latest manuscript, which appears at https://greenelab.github.io/scihub-manuscript/ or https://greenelab.github.io/scihub-manuscript/v/latest did update with the strikethrough.

**Comment by ctb** [comment]
ok, thank you for the thoughts! matches my understanding of the tech involved! please feel free to close this issue unless you want to revisit the text in the paper.

**Comment by agitter** [comment]
@dhimmel can you please copy part of this discussion into the response to reviewers and reference this issue so that the other reviewers and editor can follow along?  Feel free to edit the manuscript text as needed too.
