### ISSUE TITLE
Strengthen statement about "no objective system " for authorship

### ISSUE THREAD

**Issue by ctb** [greenelab/meta-review#123]
The statement "there is no objective system" reads like it could be a practical  statement as in "we haven't built one yet", while I believe (and think the authors agree with me, based on the paragraph) that no such principled objective system *can* exist. Either way this should be clarified.

**Comment by agitter** [comment]
Three quick notes for myself as I work on this issue
- We do want to claim that no single principled objective system _can_ exist
- The recent review about collaborative writing demonstrates different approaches, supporting that there will not be a one-size-fits-all solution (#110)
- Now that we have more Manubot manuscript examples (#128), we can point to different strategies other groups have used to determine authorship and author order, including meta-review and deep-rules
