### ISSUE TITLE
Update acknowledgements

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#126]
We should review the manubot and manubot-rootstock issues and updates to see who else should be acknowledged in the revised manuscript.  In addition, we should acknowledge the public reviewer.

**Comment by agitter** [comment]
I propose we also ask John MacFarlane if we can acknowledge him.  He has been very helpful with pandoc usage or debugging.

**Comment by dhimmel** [comment]
> I propose we also ask John MacFarlane if we can acknowledge him. He has been very helpful with pandoc usage or debugging.

Agreed. @jgm would you be okay with us acknowledging you in our manuscript describing the Manubot tool? We'd add it to [this section](https://greenelab.github.io/meta-review/v/c4baa224a99d86d88e32c2dab67245c47838fbde/#acknowledgments). Manubot uses pandoc along with other open source tools to create automated workflows for scholarly publishing. Thanks for your help across many pandoc issues over the last year or so!

**Comment by jgm** [comment]
Sure, no objections!

**Comment by agitter** [comment]
As a reminder to myself, we should also remove Dongbo from the acknowledgements when we add him as an author.

**Comment by agitter** [comment]
@zach-hensel we're revising a manuscript describing Manubot and collaborative writing.  Can we add you to the acknowledgments for your help with Manubot testing and debugging?

**Comment by agitter** [comment]
I can update the text when it is time. @dhimmel and @vincerubinetti can you please help me recall any other new manubot or rootstock contributors?

**Comment by dhimmel** [comment]
> can you please help me recall any other new manubot or rootstock contributors?

@lierdakil has provided helpful advice in several discussions such as https://github.com/manubot/rootstock/pull/196#issuecomment-475473699 and https://github.com/lierdakil/pandoc-crossref/issues/30#issuecomment-124023824. @lierdakil want to give this comment a thumbs up if you are okay with us acknowledging you in our [manuscript](https://greenelab.github.io/meta-review/v/d4a642efa06896209ddfa6e3d2387a58232e61f5/)?

**Comment by vincerubinetti** [comment]
Not sure the level you want to go with the acknowledgments, but a bunch of people and the Greene Lab helped me by giving feedback on the logo and front-end. We've also had a few people point out small bugs.

**Comment by agitter** [comment]
@vincerubinetti we tend to be very inclusive with acknowledgements, especially for this manuscript.  If you think of anyone, please feel free to tag them here so they can indicate their approval for being included, as @dhimmel and I did above.

**Comment by vincerubinetti** [comment]
@ypar @cgreene @zietzm @ajlee21 @ben-heil @zach-hensel @gwaygenomics

**Comment by agitter** [comment]
@ypar @ajlee21 @ben-heil we tagged you in this issue to ask whether it is okay for us to acknowledge your help in our [manuscript ](https://greenelab.github.io/meta-review/v/4caa4b52b2da59c136b8febaa8011eb7a0e506ee/) describing the Manubot software.  If you agree, please confirm in this issue how you would like your name to appear in the acknowledgements text.

(The others above are already acknowledged, to be added to acknowledgements, or authors).

**Comment by ypar** [comment]
ok for acknowledgements
name YoSon Park

**Comment by ajlee21** [comment]
I'm not sure how much I helped, so I leave the decision up to you.  If you choose to add me my name is "Alexandra J Lee"

**Comment by ben-heil** [comment]
I'm in the same boat as Alex, but if you choose to add me my name is 'Benjamin J Heil'
