### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#127]
@vincerubinetti and @dongbohu we would like to invite you to join us as authors on this manuscript describing Manubot for collaborative writing for your contributions to the front end, Zotero translation server, and other Manubot features.  It is under review at PLOS Computational Biology as a Software article.

We are generally following the [ICMJE guidelines](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) for authorship.  In addition to your Manubot contributions, I ask you you help us edit the manuscript during these revisions (as appropriate), approve the manuscript, and agree to be accountable for the work.  I will be opening a new issue to plan the revisions.

Once you approve of the manuscript and wish to join as authors, you can please add yourselves to [`metadata.yaml`](https://github.com/greenelab/meta-review/blob/master/content/metadata.yaml).  Once the revisions are finished and we are getting ready to resubmit, we will discuss everyone's cumulative contributions and the updated author order.  In the meantime, you could add yourself between Venkat and Casey as a placeholder.

Thanks for your work on Manubot.

**Comment by agitter** [comment]
@vincerubinetti and @dongbohu we're getting closer to resubmitting this paper.  Can you please review the manuscript and add your information to [`metadata.yaml`](https://github.com/greenelab/meta-review/blob/master/content/metadata.yaml) sometime in the next week if you approve?

Before submission, we will still discuss the new author order here.

**Comment by dongbohu** [comment]
@agitter, thanks. I have reviewed the manuscript and added my info.

**Comment by dhimmel** [comment]
> I have reviewed the manuscript and added my info.

Ah I see in https://github.com/greenelab/meta-review/commit/71b1744fceaa07367f7e7c90534628c1eabe0c8d. For future reference @dongbohu, please don't commit to master directly and instead submit PRs from your fork. All changes are handled through PR here, besides perhaps minor emergency changes by maintainers.

**Comment by agitter** [comment]
Before closing this issue, I'll update our Funding statement in the manuscript.

**Comment by agitter** [comment]
@dhimmel @slochower @vsmalladi @vincerubinetti @dongbohu @cgreene we now have incoming pull requests to close the last remaining reviewer issues.  I'd like us to please discuss and finalize the author order for our revised submission, which I plan to complete in the next day or two.

Because the manuscript is primarily about Manubot, I propose we use the convention that our contributions for authorship include direct contributions to this manuscript as well as contributions to the Manubot Python package, Rootstock, design, etc.

We will keep @dhimmel as first author and @cgreene and me as last authors.

@slochower and @vincerubinetti have made major contributions in different ways and should come after @dhimmel.  We need to agree how to order the two of you.
- @slochower has been involved since the creation of Rootstock and the standalone Python package, influencing the design and usage of both, reporting errors, and making modifications to add features.  He also helped edit the initial manuscript submission and worked on these revisions, such as the mega authors section, the collaborative writing platform table, the new Manubot usage video, and discussion of many other issues.
- @vincerubinetti joined more recently but has made extensive and impactful improvements to modernize the Manubot system, especially the styling and interactivity of manuscripts.  He also worked on the manuscript revisions, including Figure 3 and surrounding text.

@vsmalladi and @dongbohu also made important contributions, and we should decide how to order the two of you between @slochower / @vincerubinetti and @cgreene.
- @vsmalladi has contributed to Rootstock, most notably on DOCX support, formatting issues, and Mac OS issues.  He also tested private repos for these revisions and made some edits in the original submission.
- @dongbohu has been primarily involved in setting up and maintaining the Zotero translation-server for Manubot usage.

This is all open for discussion.  Please let me know your thoughts, or if I have omitted some of your contributions above.

**Comment by slochower** [comment]
I think you did a fair job summarizing. I’m happy with whatever order prevails; glad to be part of this team.

**Comment by vsmalladi** [comment]
I am good with what ever order.

**Comment by dongbohu** [comment]
Whatever order is good for me. Thanks.

Dongbo

**Comment by vincerubinetti** [comment]
Doesn't matter to me. Dealer's choice.

**Comment by agitter** [comment]
Thank you everyone for being so flexible regarding the ordering.  I talked to @dhimmel to better understand the extent of the development efforts that were needed for the front end improvements and translation server.  Based on that, I propose:

@dhimmel @vincerubinetti @slochower @dongbohu @vsmalladi @cgreene @agitter 

I'll make a pull request to update the authors.  In addition, @dhimmel and I will be co-corresponding (#208).
