### ISSUE TITLE
Public demo manuscript

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#155]
I really liked the [PSB workshop manuscript](https://github.com/dhimmel/psb-manuscript/) @dhimmel set up to teach Manubot to potential users.  Should we consider creating a `manubot/demo` manuscript that we could advertise in this paper?

The pros would be that it could help us attract users by showing them how easy editing is once a manuscript is set up.  The cons would include the @manubot organization members needing to monitor it and approve pull requests.  We could set some rules to help make it easier to approve pull requests, like forbidding images so that we wouldn't have to check the licensing.

**Comment by dhimmel** [comment]
> We could set some rules to help make it easier to approve pull requests

We don't want it to become like https://github.com/illacceptanything/illacceptanything? haha!

> Should we consider creating a `manubot/demo` manuscript that we could advertise in this paper?

I think this is a great idea. I can set it up.

> like forbidding images so that we wouldn't have to check the licensing.

Sometimes it's helpful for users to be able to play around with figures, but yes we could be strict should licensing confusion become an issue.

At least at the beginning, the time required to maintain this repo should be minimal.

**Comment by agitter** [comment]
> At least at the beginning, the time required to maintain this repo should be minimal.

And if there is a lot of activity, that would be a good problem to have.  Reviewing demo pull requests would also be a low-commitment way for someone to contribute to the @manubot org.

**Comment by vsmalladi** [comment]
That is a great idea.

**Comment by vincerubinetti** [comment]
Would it make sense to combine this in some way with https://github.com/manubot/rootstock/pull/169 ?

**Comment by agitter** [comment]
@vincerubinetti I'm not strongly opposed to combining them, but I do see the two example manuscripts as serving different purposes.  The demo's goal would be to encourage prospective users to experiment with citations, formatting, pull requests, etc.  It could get quite long and messy.  The example in the `rootstock` repository is a carefully-curated document showcasing Manubot/Markdown/Pandoc's features.

**Comment by agitter** [comment]
@dhimmel I assigned you to this issue based on your response above.  If you can't set this up before we resubmit, I could work on it instead.

**Comment by agitter** [comment]
I suggest we create a new `Getting started with Manubot` subsection that can expand upon the current sentence:

> An example repository demonstrates Manubot’s features and serves as a template for users to write their own manuscript with Manubot.

We can reference this new public demo and the discussion in #104, including the newly expanded `02.delete-me.md` that illustrates Manubot's features.

**Comment by dhimmel** [comment]
I like the idea of a "Getting started with Manubot". I can write this. We'll also note in this section that the manubot architecture may change drastically, but we will try to make migration manageable and will provide migration support to existing manuscripts.

What should we name the repo? Some possibilities:

- `manubot/demo`
- `manubot/sandbox`
- `manubot/practice`

**Comment by agitter** [comment]
I like `manubot/practice` because it acts as an invite for users to actively modify the content.  `manubot/try-me` would convey the same thing but doesn't sound very good.

`manubot/demo` is my second choice.

**Comment by dhimmel** [comment]
I like `try-me`. Let's get some input from @slochower @vincerubinetti @cgreene @vsmalladi.

**Comment by slochower** [comment]
I like `manubot/try-me` (it's in the spirit of `02.delete-me.md`).

**Comment by vincerubinetti** [comment]
`manubot/playground`?

**Comment by agitter** [comment]
That's another good suggestion.  My new ordering is:
1) `try-me`
2) `playground`
3) `practice`

I'd be happy with any of those.  We could also be more explicit and use `manubot/try-manubot`.

**Comment by dhimmel** [comment]
`try-manubot` is descriptive. I also like `playground`, but think it's a bit less descriptive.

**Comment by dhimmel** [comment]
Okay I created https://github.com/manubot/try-manubot. Still need to create a PR that updates the README documentation.
