### ISSUE TITLE
Update to latest version of front-end from manubot/rootstock

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/meta-review#187]
At some point before final review or publishing, the manuscript should be updated to the latest front-end from `manubot/rootstock`.

Not too much has changed between the current `meta-review` version and the `rootstock` version, but there are some slight improvements.

**Comment by agitter** [comment]
Good suggestion.  It looks like there aren't any incoming pull requests in rootstock so we could do this any time.

**Comment by agitter** [comment]
We can update once more before resubmitting to pull the latest rootstock changes.
