### ISSUE TITLE
Track changes from initial to revised journal submission

### ISSUE THREAD

**Issue by dhimmel** [greenelab/meta-review#198]
I am guessing we'll need a tracked changes document.

I'd like to give this a try, since it's something we've been trying to improve in https://github.com/manubot/rootstock/issues/54.

**Comment by agitter** [comment]
Thanks, that would be great.  You're correct that we will need to submit a document with changes tracked.

**Comment by dhimmel** [comment]
# Generating a DOCX for v2.0 release

In case we can't get pandiff to work fully in #200, here's a DOCX for our previous submission. We can use it to "compare changes" in libreoffice or ms word.

```sh
# Checkout tag corresponding to past master branch commit
git checkout v2.0
# Checkout files for output directory from output branch
git --work-tree=output checkout 937c297c6deed1126f4ef7322e3830f406e3df81 -- . && git reset

# Run DOCX export (copied from build.sh)
CSL_PATH=build/assets/style.csl
DOCX_PATH=build/assets/pandoc-reference.docx
BIBLIOGRAPHY_PATH=output/references.json
INPUT_PATH=output/manuscript.md
pandoc --verbose \
--from=markdown \
--to=docx \
--filter=pandoc-fignos \
--filter=pandoc-eqnos \
--filter=pandoc-tablenos \
--bibliography=$BIBLIOGRAPHY_PATH \
--csl=$CSL_PATH \
--metadata link-citations=true \
--reference-doc=$DOCX_PATH \
--resource-path=.:content \
--output=output/manuscript.docx \
$INPUT_PATH
```

Produced [`output/manuscript.docx`](https://github.com/greenelab/meta-review/files/3060946/manuscript.docx). Note I didn't use exactly the same environment as Travis would have run, but content-wise, this should be the DOCX of our [v2.0 release](https://github.com/greenelab/meta-review/releases/tag/v2.0).

**Comment by slochower** [comment]
Ack. Why does the v2.0 release have "Overleaf v1" in the table header?

Edit: something wrong with the merge of #188 or a subsequent merge.

**Comment by slochower** [comment]
Quite a few bugs with figures when viewing with LibreOffice. For example, the text on Figure 2 is missing. I don't think this should be a showstopper for us, but DOCX export and/or rendering has a ways to go.

![image](https://user-images.githubusercontent.com/5393995/55835095-27445d80-5ad0-11e9-822e-ba65ebeca517.png)

**Comment by agitter** [comment]
> Quite a few bugs with figures

I noticed that when we resubmitted deep review as well.   The pandoc DOCX was not as good as copying the HTML into Word.

**Comment by dhimmel** [comment]
The [v2 release](https://github.com/greenelab/meta-review/releases/tag/v2.0) is based on https://github.com/greenelab/meta-review/commit/12fd1685f01d992e37f997a1daf6b523e1dc152a from Oct 23, 2018. It corresponds to our initial submission to PLOS Comp Bio I believe. Our revised submission will be v3.0 I'm guessing.

> Quite a few bugs with figures when viewing with LibreOffice

Yes, probably since it struggles embedding / converting SVGs. I am guessing we will delete the figures but keep the captions for the purposes of submission.

**Comment by slochower** [comment]
> Our revised submission will be v3.0 I'm guessing.

Whoops, my mistake.

> The pandoc DOCX was not as good as copying the HTML into Word.
> Yes, probably since it struggles embedding / converting SVGs. 

Right, in the future, DOCX build could also do a SVG/PDF to PNG step.

**Comment by agitter** [comment]
I was curious how well comparing the PDFs outputs directly would work.  Adobe Acrobat Pro reported the documents were too complex.  However, Draftable did a fairly good job: https://draftable.com/compare/ULkhUzDXzEml

The figure changes were missed and there are some formatting changes that are needlessly annotated, but the references and text are handled well.

**Comment by dhimmel** [comment]
Draftable does work surprisingly well. I do think the split diff makes it a bit challenging to fully reason what the change is compared to a unified diff:

> ![image](https://user-images.githubusercontent.com/1117703/55900403-1f022600-5b95-11e9-8a5b-bbae637c8b1f.png)

**Comment by agitter** [comment]
I also doubt that the Draftable link is persistent, so it does not seem like a good option for sharing the tracked changes with reviewers.
