### ISSUE TITLE
Update figshare screen recording metadata

### ISSUE THREAD

**Issue by dhimmel** [greenelab/meta-review#207]
@slochower created a screen recording to address https://github.com/greenelab/meta-review/issues/139, which we added to the manuscript in https://github.com/greenelab/meta-review/pull/191. Version 1 is at https://doi.org/10.6084/m9.figshare.7946192.v1

I'd like to do the following:

+ @slochower move current deposit to the [Manubot Figshare Project](https://figshare.com/account/home#/projects/62288). You can do this by checking the box under my data and using the Actions dropdown.

+ I will propose some more complete metadata including a different title and changed metadata.

+ I will add a snapshot, such that the video embed can default to showing the video title rather than a black screen.

**Comment by slochower** [comment]
Yes, smart.

> @slochower move current deposit to the Manubot Figshare Project. You can do this by checking the box under my data and using the Actions dropdown.

I got the notification and already moved it to the Manubot project before I saw this. However, now it is marked private. I'm not sure if this is a project-level setting or not.

> I will propose some more complete metadata including a different title and changed metadata.

Okay...

> I will add a snapshot, such that the video embed can default to showing the video title rather than a black screen.

Sounds good.

**Comment by dhimmel** [comment]
Made project public at https://figshare.com/projects/Manubot/62288

**Comment by dhimmel** [comment]
@slochower I don't see a way to edit https://figshare.com/account/projects/62288/articles/7946192.

> ![image](https://user-images.githubusercontent.com/1117703/55911406-9a240600-5bae-11e9-8ad7-05248d3cddef.png)

Perhaps you need to add me as an author? Sometimes the figshare interface leaves a bit to be desired!

**Comment by agitter** [comment]
The journal resubmission instructions include
> Supporting Information uploaded as separate files, titled 'Dataset', 'Figure', 'Table', 'Text', 'Protocol', 'Audio', or 'Video'.

I was not planning to upload this video because it is already available on figshare.  Is that our intention, or should I also upload it as a video?  The journal might make a second copy on figshare in that case.

**Comment by dhimmel** [comment]
One benefit of including it is that it could show up in the Figshare element at the bottom of the page ([example](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004259)):

> ![image](https://user-images.githubusercontent.com/1117703/55912525-d6f0fc80-5bb0-11e9-9e66-008aa7f4a1ea.png)

Ideally, PLOS could include a figshare item in the "Supporting Information" section without having to re-upload it. Not sure if this is possible.

The ideal situation:

1. video playable from journal HTML view
2. no re-upload to figshare

However, I'd rather have 1 without 2 than neither.

**Comment by slochower** [comment]
> Perhaps you need to add me as an author? Sometimes the figshare interface leaves a bit to be desired!

Hmm... looking...
Just checking, you don't see anything here?
![image](https://user-images.githubusercontent.com/5393995/55913500-a0f44e00-5b99-11e9-91bc-d748981654f8.png)

I added you as an author, but I think that's only for the metadata. Still, check again to see if you have any additional options.

**Comment by dhimmel** [comment]
I still don't see how to edit, so I created a [ticket](https://support.figshare.com/support/tickets/96301) (ticket link will only work for me):

> ![image](https://user-images.githubusercontent.com/1117703/55914681-c1320600-5bb5-11e9-9fce-4d20cf0cd6e4.png)

**Comment by agitter** [comment]
I found an example manuscript with supporting videos: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006068#sec013

They do play in the figshare widget.  I expect that we would have to re-upload the video to get that, which is acceptable.

However, their [instructions](https://journals.plos.org/ploscompbiol/s/supporting-information#loc-multimedia-files) request videos of at most 10 MB.  I'll see what options we have to submit as is, but the submission system may not accept it.

**Comment by slochower** [comment]
I can perhaps fiddle with the export resolution until it is that small, but my fear (without actually checking) is that bumping the resolution that far down will make the webpage text in the video unreadable. At which point, it may be better to make a new version.

**Comment by agitter** [comment]
Let's keep the current resolution for the resubmission.  I agree that we need reasonable resolution to keep the text readable, and I'll explain that if they push back.

**Comment by dhimmel** [comment]
Radu Gheorghiu, an Integrations Engineer at Figshare, responded to my help ticket and wrote:

> I have checked and the item that you are trying to edit was created by David Slochower. He is the owner of the item and therefor only he can edit it. At the moment, one item cannot have multiple owners. The ability of having multiple collaborators editing the metadata of the same item, within Projects, is being discussed  internally, but unfortunately we cannot make an estimation of when this feature will be available. We could move the item to your account, so that you can edit it, but this can be done only if David requests it specifically by sending an email request to support@figshare.com.

I didn't realize there was no way for multiple figshare accounts to edit the same item. Too bad. Therefore, I can just leave what updates I think we should make in a comment here that @slochower can apply to the record. Feel free @slochower to remove me as an author, since that didn't accomplish what we were hoping.

**Comment by dhimmel** [comment]
@slochower how about the following? Feel free to change a bit. Also you should be able to show us unpublished version by link before finalizing.

Title: "How to edit a manuscript on GitHub with Manubot"

Description:

***
The screen recording shows how to edit a manuscript via GitHub using Manubot. Manubot is the the manuscript bot for automated scholarly publishing. It is an open source software project for writing scholarly documents using GitHub. Learn more at https://manubot.org.

This screen recording is used as a supporting data video for the manuscript describing Manubot at https://greenelab.github.io/meta-review/.

This latest version of this Figshare item is available at https://doi.org/10.6084/m9.figshare.7946192 or shortened to https://doi.org/c4fz.
***

Add a PNG high-rez screenshot as second file like (but same dimensions as video):

> ![image](https://user-images.githubusercontent.com/1117703/55982445-ee8abc80-5c66-11e9-8a06-1129ad955ae8.png)

This will be used as the clip to show before video is played.

Probably want to rename files to

+ `editing-with-manubot-via-github.mp4`
+ `editing-with-manubot-via-github.png`

In case we ever want to add more videos to this record.

**Comment by slochower** [comment]
- ✓ Updated Title
- ✓ Updated Description

Note: The link  https://doi.org/10.6084/m9.figshare.7946192 goes to the original movie, before I moved it to the Manubot project. However, if I go to "Cite" on the Manubot project version, it gives me the _same_ DOI. I clearly am having difficulty with the FigShare UI. Is this because the version in the Manubot project is still marked private?

![image](https://user-images.githubusercontent.com/5393995/55984110-90071380-5c51-11e9-807e-4255d42df59d.png)


- ✓ Uploaded PNG for title (the so the object is now a "file set"). I'm not sure whether this will affect autoplaying or not.
- ✗There appears to be no way to actually change the movie filename as uploaded. It is not an editable field.

**Comment by dhimmel** [comment]
The DOI link will direct to the latest published version. The private
version is not published yet.

Regarding rename, you must delete file and upload with changed name.

**Comment by slochower** [comment]
Won't either of these things (re-publishing or re-uploading) give a new DOI? Just making sure we propagate the changes...

**Comment by dhimmel** [comment]
Re-uploading in the same item should not automatically publish. Isn't there
a publish button? I believe the publish button should create a v2 rather
than a new record

**Comment by slochower** [comment]
I think the private version should now have the files correctly named.

**Comment by dhimmel** [comment]
Okay the private version now looks good to me. One small change: can you reorder the files to make the video come first? This will make it possible to directly watch the video from the landing page. I think the upload page supports drag and drop reordering. No worries if this doesn't seem possible. @slochower proceed with v2 publication.

**Comment by slochower** [comment]
Should be good.

**Comment by slochower** [comment]
But I think maybe you have to make it public.

**Comment by dhimmel** [comment]
Great published at https://doi.org/10.6084/m9.figshare.7946192.v2

> But I think maybe you have to make it public.

I don't think so, but let me know if otherwise.

**Comment by slochower** [comment]
Well, I see it is public now, but even after I clicked Publish, it still said Private, and I couldn't find any way to change that. Could be ineptitude on my part. Anyhow, nice work.

**Comment by slochower** [comment]
See #213 to remove the DOI to version 1. The unversioned DOI should point to the latest version, which is probably what we want.
