### ISSUE TITLE
Figure formats for resubmission

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#209]
I reviewed the resubmission instructions, which include
> Figures uploaded separately as TIFF or EPS files (if you wish, your figures may remain in your main manuscript file in addition).

**Comment by dhimmel** [comment]
Okay we should make a directory in the repo like `plos-comp-bio`, where we can upload files like `plos-comp-bio/figures/figure-1.tiff`. I can open a PR to do this.

**Comment by agitter** [comment]
We also have multiple copies of these figures in different formats in `content/images` already.  That would be another option.

**Comment by dhimmel** [comment]
> We also have multiple copies of these figures in different formats in content/images already

Yes but these get copied to the `webpage` branch so I'm a bit worried about bloat. I'm guessing we'll also want to track other files like submitted documents / diffs / etcetera, so a separate folder may make sense.

**Comment by agitter** [comment]
Got it 👍
