### ISSUE TITLE
Competing interests

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#215]
The journal requests a competing interests statement.  No one has raised competing interests yet, but can you please give a thumbs up here to confirm you do not have any?  In that case I'll enter:
> The authors have declared that no competing interests exist.

@dhimmel @vincerubinetti @slochower @dongbohu @vsmalladi @cgreene

**Comment by dhimmel** [comment]
For more info on what competing interests are see [this page](http://web.archive.org/web/20190412164758/https://journals.plos.org/ploscompbiol/s/competing-interests).

> At the time of submission, authors must list all competing interests relevant to the submitted research. Examples may include but are not limited to:
> 
> Names of all funding sources
> 
> Description of funder’s role in the study design; collection, analysis, and interpretation of data; writing of the paper; and/or decision to submit for publication
> 
> Whether they have served or currently serve on the editorial board of the journal to which they are submitting
> 
> Whether they have acted as an expert witness in relevant legal proceedings
> 
> Whether they have sat or currently sit on a committee for an organization that may benefit from publication of the paper
> 
>

**Comment by agitter** [comment]
@dongbohu can you please give final confirmation that you have no competing interests for the Manubot paper?  Competing interest are defined above.

**Comment by dongbohu** [comment]
Done (sorry I was out of town today).
