### ISSUE TITLE
Contributor roles

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#217]
For the resubmission, we need to map authors to contributor roles:

Conceptualization	
Data curation	
Formal analysis	
Funding acquisition	
Investigation	
Methodology	
Project administration	
Resources	
Software	
Supervision	
Validation	
Visualization	
Writing – original draft	
Writing – review & editing

**Comment by dhimmel** [comment]
Defined at https://journals.plos.org/ploscompbiol/s/authorship:

| Contributor Role | Role Definition |
|--------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Conceptualization | Ideas; formulation or evolution of overarching research goals and aims. |
| Data Curation | Management activities to annotate (produce metadata), scrub data and maintain research data (including software code, where it is necessary for interpreting the data itself) for initial use and later reuse. |
| Formal Analysis | Application of statistical, mathematical, computational, or other formal techniques to analyze or synthesize study data. |
| Funding Acquisition | Acquisition of the financial support for the project leading to this publication. |
| Investigation | Conducting a research and investigation process, specifically performing the experiments, or data/evidence collection. |
| Methodology | Development or design of methodology; creation of models |
| Project Administration | Management and coordination responsibility for the research activity planning and execution. |
| Resources | Provision of study materials, reagents, materials, patients, laboratory samples, animals, instrumentation, computing resources, or other analysis tools. |
| Software | Programming, software development; designing computer programs; implementation of the computer code and supporting algorithms; testing of existing code components. |
| Supervision | Oversight and leadership responsibility for the research activity planning and execution, including mentorship external to the core team. |
| Validation | Verification, whether as a part of the activity or separate, of the overall replication/reproducibility of results/experiments and other research outputs. |
| Visualization | Preparation, creation and/or presentation of the published work, specifically visualization/data presentation. |
| Writing – Original Draft Preparation | Creation and/or presentation of the published work, specifically writing the initial draft (including substantive translation). |
| Writing – Review & Editing | Preparation, creation and/or presentation of the published work by those from the original research group, specifically critical review, commentary or revision – including pre- or post-publication stages. |

I'll open a PR to add this to metadata.yaml.

**Comment by dhimmel** [comment]
The comment on contributions at https://github.com/greenelab/meta-review/issues/127#issuecomment-480501901 may be helpful

**Comment by cgreene** [comment]
I imagine I am:
* Conceptualization
* Funding Acquisition
* Writing -- Original Draft Preparation
