### ISSUE TITLE
Refer to the Deep Review explicitly

### ISSUE THREAD

**Issue by dhimmel** [greenelab/meta-review#22]
From https://github.com/greenelab/meta-review/pull/16#discussion_r146103301 by @agitter 

> I think we've been using generic terms like "open review" and "review manuscript" and haven't referred to this as "Deep Review". We should introduce that term early on if you want to use it here.

My opinion is that we should explicitly refer to the Deep Review, early and often. This will make the manuscript more concrete and will help associate it with the Deep Review's burgeoning brand.

**Comment by agitter** [comment]
Deep Review works for me internally, but I considered it too ambiguous to use externally.  I'm fine using it as long as we introduce it in the second intro paragraph.  Having the specific name will make other sections more readable.
