### ISSUE TITLE
knitcitations

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#222]
https://github.com/cboettig/knitcitations enables cite by DOI or URL for Rmarkdown.  We should find a place to mention it as related existing work.

**Comment by dhimmel** [comment]
Ah yes, I used `knitcitations` back in the day when I was more of an R user, see https://github.com/cboettig/knitcitations/issues/73. It is one of the early cite-by-identifier implementations I used. Another was the [Thinklab platform](https://think-lab.github.io), which is now shut-down.
