### ISSUE TITLE
Publish peer review history 

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#224]
@dhimmel pointed out that PLOS journals created an option to [publish peer reviews](https://blogs.plos.org/plos/2019/05/plos-journals-now-open-for-published-peer-review/) alongside a manuscript.  It officially starts for manuscripts submitted after May 22, but I will inquire whether we can have our peer review history published.  It is already fully public.

**Comment by dhimmel** [comment]
In the meantime, if any readers are interested in the peer reviews and our responses, see [`response-to-reviewers.md`](https://github.com/greenelab/meta-review/blob/master/content/response-to-reviewers.md).

The reviewers reviewed the [revised manuscript](https://github.com/greenelab/meta-review/releases/tag/v3.1) and submitted these comments:

> Reviewer 1: Great updates to the manuscript!
> 
> Reviewer 2: Thanks for having answered all my questions and addressed my comments. I'm plainly satisfied and I've no further question nor comment. You've designed a great tool for the community.
> 
> Reviewer 3: Thank you for addressing all of my concerns!

We received these reviews today with the note:

> We are pleased to inform you that your manuscript 'Open collaborative writing with Manubot' has been provisionally accepted for publication in PLOS Computational Biology.

**Comment by agitter** [comment]
I asked the editors if we can publish our peer reviews when I resubmitted the formatting changes.

**Comment by agitter** [comment]
The PLOS staff said we will not be able to use this option to publish the peer reviews:

> Thank you for your response. Only manuscripts that were initially submitted on or after May 22 of this year so your manuscript is unfortunately not eligible to opt in to published peer reviews. I apologize for any confusion that may have caused.
