### ISSUE TITLE
Metadata verification

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#229]
I'm lumping all of the metadata verification requests together.  We can split these if necessary:
- [x] Author contributions
- [x] Early version
- [x] Financial disclosure
- [x] Competing interests #215 
- [x] Data availability
- [x] Corresponding authors
- [x] Authorship and affiliation
- [x] Protocols
- [x] Title and short title

> Please confirm that the following information is correct and contact us if any changes are necessary. This information will be indexed in PubMed and published by PLOS Computational Biology as you have written them.

> Your Author Contributions will be typeset as follows:
o	Conceptualization: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter
o	Data curation: D.S. Himmelstein, A. Gitter
o	Formal analysis:
o	Funding acquisition: D.S. Himmelstein, C.S. Greene
o	Investigation: D.S. Himmelstein, D.R. Slochower, A. Gitter
o	Methodology: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter
o	Project administration: D.S. Himmelstein, C.S. Greene, A. Gitter
o	Resources: C.S. Greene
o	Software: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, D. Hu, V.S. Malladi, A. Gitter
o	Supervision: D.S. Himmelstein, C.S. Greene, A. Gitter
o	Validation: D.S. Himmelstein, V.S. Malladi, A. Gitter
o	Visualization: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter
o	Writing original draft: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, C.S. Greene, A. Gitter
o	Writing review & editing: D.S. Himmelstein, V. Rubinetti, D.R. Slochower, V.S. Malladi, C.S. Greene, A. Gitter

> An Early Version of your manuscript:
o	WILL be published online ahead of the final version 

> If you (or your institution) are planning a press release for this article, please contact us as soon as possible to ensure that an early version of your paper is not published. 

> Your financial disclosure will be typeset as follows:
DSH, DH, VR, and CSG were supported by Grant G-2018-11163 from the Alfred P. Sloan Foundation and Grant GBMF4552 from the Gordon and Betty Moore Foundation. VSM was supported by Grant RP150596 from the Cancer Prevention and Research Institute of Texas. The funders had no role in study design, data collection and analysis, decision to publish, or preparation of the manuscript.

> Your competing interests statement will be typeset as follows:
The authors have declared that no competing interests exist.

> Your data availability statement will be typeset as follows:
The source code and data for this manuscript are available at https://github.com/greenelab/meta-review and archived via Software Heritage identifier swh:1:dir:5e644c3a487081b272b2c9b52bcd55caa89c4f85. Source code for Manubot resides in the following repositories: https://github.com/manubot/manubot (GitLab mirror (https://gitlab.com/manubot/manubot) archived at swh:1:dir:1eb3b7e6d7e21239fedccf25a186af622ee6912e, packaged on PyPI (https://pypi.org/project/manubot/)), and https://github.com/manubot/rootstock (GitLab mirror (https://gitlab.com/manubot/rootstock), archived at swh:1:dir:cfc3af2e8e1a0d9b639fdab0943731e608910731).

> The details of the corresponding author will be typeset as follows:
o	Name Daniel S. Himmelstein, Anthony Gitter
o	E-mail daniel.himmelstein@gmail.com (DSH); gitter@biostat.wisc.edu (AG)
o	ORCiD 0000-0002-3012-7446, 0000-0002-5324-9833

> Please check the authorship and affiliations list on the title page of your manuscript. These details will be used to index the authorship of your manuscript and therefore should be checked carefully for any errors.

> Please ensure that if you have any protocols associated with protocols.io in your manuscript, they are made public before publication to guarantee immediate access to the methodological details.

> Your title will be typeset from the submission system, not the manuscript file. Please check that the following is correct:
Open collaborative writing with Manubot

> Your short title will be typeset from the submission system, not the manuscript file. Please check that the following is correct:
Open collaborative writing with Manubot 

> Please note that if you wish any word to be italicised, this will need to be manually changed in the Editorial Manager system. Please contact the journal office to address this.

**Comment by agitter** [comment]
@slochower and @vsmalladi can you please help double check and proofread the metadata here?  I'll also look it over before we close the issue.

**Comment by slochower** [comment]
The metadata looks good. We could consider updating the Software Heritage links. I can't quite tell whether that SH link goes to a specific commit or whether it is just showing me the latest commit that is archived. I can look into this.

**Comment by dhimmel** [comment]
> We could consider updating the Software Heritage links

Ah yes, I should check if they've been updated. The SH link does go to a specific commit.

**Comment by vsmalladi** [comment]
The metadata looks good.
