### ISSUE TITLE
Remove figures from text

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#232]
> Your figures are currently included within your article file. Please remove them from your article file and upload them as separate figure files. At this time, we can only accept figures under 10 MB each in .TIF (preferred) and .EPS format. For additional details, please see our figure guidelines: http://journals.plos.org/ploscompbiol/s/figures. Additionally, please ensure that you have included a corresponding caption/legend in the manuscript file.

Do we want to do this manually in the .docx file we submit?

**Comment by dhimmel** [comment]
> Do we want to do this manually in the .docx file we submit?

Yes. Because we need to keep the captions right?

**Comment by agitter** [comment]
Closing this issue.  I'll do it manually.
