### ISSUE TITLE
Reference format

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#233]
> Your references need to be formatted according to the PLOS style. PLOS uses the numbered citation (citation-sequence) method and first six authors, et al. Authors should be listed as "Last name, First Initial". If using EndNote, please use the following style file: https://endnote.com/style_download/plos-public-library-of-science-all-journals/

See https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fplos-computational-biology

**Comment by dhimmel** [comment]
See https://github.com/greenelab/meta-review/pull/228

**Comment by dhimmel** [comment]
More info at https://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-references

**Comment by agitter** [comment]
One formatting question I'm still unclear about is whether they will take all of our inline links throughout the text.  Do we need to reformat those as URL citations?

**Comment by dhimmel** [comment]
> Do we need to reformat those as URL citations?

I'm opposed to polluting our reference section with hyperlinks. Is there any indication that PLOS CB want us reformat hyperlinks as citations?

I would say we just wait to the proof stage to see if they make it though. I think their system is technically capable of publishing hyperlinks, although there is a chance they get removed by the default workflow.

**Comment by agitter** [comment]
No, I haven't seen any indication that they want us to change the hyperlinks.  I checked a few papers from their current home page and saw that they write out the URL for hyperlinks:

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007044
- `OpenCV ver. 3.3.1 (https://opencv.org/).`
- `ImageJ (https://imagej.nih.gov)`

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007056
- `Los Alamos HIV Database (http://www.hiv.lanl.gov/)`
- `PyMol (https://pymol.org/2/)`

I'm okay leaving our links in their current format for the resubmission.
