### ISSUE TITLE
Striking image

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#235]
Do we want to to prepare an image for the journal website?  We may want one for manubot.org anyway.  I'm okay skipping this if none of us have time to work on a figure in the short term.

**Comment by dhimmel** [comment]
From https://github.com/greenelab/meta-review/issues/226#issuecomment-497856572:

> You can also be able to upload a Striking Image to accompany your article if one is available. If this image is judged to be suitable, it may be featured on our website. Images should be high resolution, eye-catching, single panel images. If your image is from someone other than yourself, please ensure that the artist has read and agreed to the terms and conditions of the Creative Commons Attribution License. Note: we cannot publish copyrighted images.

It could include the Manubot logo. Possibly it could be one of the images that we're planning to create for the [manubot homepage](https://github.com/manubot/manubot.org). CC @vincerubinetti.

I think we might as well submit something, but not go too much out of our way... so something we've already created or will end up creating anyways.

**Comment by agitter** [comment]
Is there anything in https://github.com/manubot/manubot.org/pull/11 we may want to use as a striking image?  [automated-1.png](https://github.com/manubot/manubot.org/blob/275d235415f0287fb5cebe8f2fb58ba4fee9d324/images/automated-1.png) is my favorite so far.  I realize more images are incoming too.

**Comment by dhimmel** [comment]
> Is there anything in manubot/manubot.org#11

Yes I think there are several good options there. My preferences in order:

1. [`automated-1.png`](https://github.com/manubot/manubot.org/blob/fa48ae3bbef46c4b2a6de152c6553a642c847903/images/automated-1.png)
2. [`open-1.png`](https://github.com/manubot/manubot.org/blob/fa48ae3bbef46c4b2a6de152c6553a642c847903/images/open-1.png)
3. somthing like [`interactive-2.png`](https://github.com/manubot/manubot.org/blob/fa48ae3bbef46c4b2a6de152c6553a642c847903/images/interactive-2.png) but of the Meta Review.

@agitter this is a small detail and may not ever be used, so you should go ahead and pick whatever you think is best at time of re-submission.

**Comment by slochower** [comment]
+1 for `automated-1.png`

**Comment by agitter** [comment]
Let's use `automated-1.png` as the striking image.  I'm leaving this open until I upload it into the submission system.
