### ISSUE TITLE
PLOS proofing watchlist

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#244]
There are a few specific issues I would like to monitor in the proofs.  One is how the hyperlinks are handled in text.  Another is the Software Heritage archive links.  In the DOCX version of the manuscript the origin portion of the links is converted from `https://` to `https:/`.  I was unable to manually correct this.

**Comment by agitter** [comment]
In https://github.com/greenelab/meta-review/issues/246#issuecomment-505195955 there were two issues with our source document I noted that we should correct:
- doi:10.6084/m9.figshare77 is the wrong DOI
- we use both "web page" and "webpage"

**Comment by dhimmel** [comment]
> doi:10.6084/m9.figshare77 is the wrong DOI

Wow super bizarre. This [was happening before](https://greenelab.github.io/meta-review/v/bdeae8936b61a425f311cff022872984f73ab580/#ref-15nwuvjrA) we applied the PLOS CSL, but we seem to be correctly citing `doi:10.6084/m9.figshare.5346577`. I think I must have deleted some characters accidentally in the manual references file.

**Comment by dhimmel** [comment]
> we use both "web page" and "webpage"

I have a slight preference for webpage, but @agitter pick whatever you think is best.

**Comment by agitter** [comment]
"webpage" works for me.  I'll add that to the proofs.

**Comment by agitter** [comment]
Closed by #247 and the manual corrections in #246
