### ISSUE TITLE
Formal acceptance and proofs

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#246]
Congratulations everyone!  All authors already received news of the formal acceptance to PLOS Computational Biology.

I paid the publishing fee and also received the proofs today.  The most
important information is that the uncorrected proof will post June 24 on PLOS Computational Biology and they request proofs back by June 25 so that the corrected version can appear on July 5.

I'll review the proofs on Monday, watching for #244.  If anyone else wants to help review the proofs, please send me your annotations.  I'll aggregate and return them.

[Annotation guidelines](https://github.com/greenelab/meta-review/files/3315921/Author.proof.annotation.guidelines.pdf)
[Proofs](https://github.com/greenelab/meta-review/files/3315922/pcbi.1007128.pdf)

<details>
<summary>Complete proof notification (lightly edited)</summary>

The PDF proof of your PLOS Computational Biology article, Open collaborative writing with Manubot, is ready for your review. Please review the proof carefully. Only one set of changes, and only from the corresponding author or another proxy, will be accepted.

Acceptable corrections are limited to author name or affiliation errors, misleading scientific inaccuracies, and printer's errors. Change requests beyond these items will not be accepted. 
Since you have agreed to publish an early version of your article, a copy of your uncorrected proof will be available on Jun 24, 2019 via the PLOS Computational Biology website. Please review and return your proof by Jun 25, 2019 so that a corrected version of your article can be posted on Jul 05, 2019.

Instructions for Accessing, Editing & Returning PDF: 
1.	Click HERE to access your PDF Proof: [removed]
2.	Select the file, then click the Download Files button. Be sure to save the file to your computer! 
3.	If changes are not required: 
o	Type “no author corrections” in the Task Completion Notes field. 
o	Then click the Complete Task button. 
4.	If changes are required: 
o	Only Adobe Acrobat Commenting Tools are accepted. 
o	Use these three mark-up types whenever possible (Annotations tools in Comment menu): 
	Insert new content 
	Replace existing content 
	Delete existing content (strikethrough) 
	Sticky Note (for corrections concerning Figures only) 
o	To request replacement of figures or tables (only in cases of misleading scientific inaccuracies or printer's errors), use the Sticky Note tool to explain what corrections you have made to these objects. When you upload your marked-up PDF to submit it, also upload any replacement figures or tables as separate files. Note: please ensure that figure specifications remain the same as those in your accepted files. 
5.	Click the same access link above to submit your marked-up proof into ProTrak, then: 
o	Click the Output File tab, then the Upload Files button. Note: If your version of Java is out of date, click Update in the Java Update Needed field if prompted to do so. 
o	You may drag and drop or click the Add button in the Upload File tool to upload your marked-up PDF (and other correction files if needed). 
o	Click Close. 
6.	Adding a note to the Task Completion Notes field is optional. When you are finished uploading files and adding notes, click the Complete Task button. This advances your commented proof to PLOS and closes your author proof review. 
If you have questions or concerns, please contact your journal through http://www.plos.org/contact/ with the subject line “Author Proof Query”. 
</details>

**Comment by dhimmel** [comment]
> I paid the publishing fee and also received the proofs today.

Thanks! I assumed we'd use the Sloan grant for this, but not a problem if you've taken care of it.

I'll start reviewing the uncorrected proof now.

**Comment by dhimmel** [comment]
I skimmed through and looked for the most common issues. I noticed several problems related to lossy conversion of the DOCX and some changes that introduce errors. It will be helpful for them to look at the [HTML version](https://greenelab.github.io/meta-review/v/a0c392bb2c48c69bbaafc5aa4640d64672c005e3/). For all formatting issues, they should use this as the reference for the correct formatting.

+ hyperlinks on text that is not a URL have been removed. Many of our hyperlinks, like in "existing manuscripts" are essential. Hopefully they can convert the hyperlinks from the word document. Otherwise, they will manually have to add every hyperlink, which is error prone and laborious.

+ Hyperlinks in the data availability statement have been removed and nested parenthetical statements have been introduced. If the hyperlinks must be converted to URLs here, then they should use "at" rather than "()".

+ DOI URLs were omitted for some references, including all bioRxiv references. The affected references are 2, 10, 11, 32, 42, 46, 48, 68, 72, 73, 75, 78, 86, 87.

+ Some preformatted text was converted to regular text, such as `pandoc-xnos`, dedicated `output` and `gh-pages` branches, and `{{total_commits}} Git commits`. The former doesn't need to be preformatted (i.e inline code), but the later definitely does.

+ Some preformatted text was preserved, but hyperlinks were added to DOIs and URLs in this preformatted text. Preformatted text should not have hyperlinks added to text within, unless we include those hyperlinks like for the git branch links. This occurs in Table 2 in the "Example citation" column. It also occurs in the code block on page 11 starting with `manubot cite`. This code block also has bad spacing problems. They should reference [our HTML](https://greenelab.github.io/meta-review/v/a0c392bb2c48c69bbaafc5aa4640d64672c005e3/#citation-utilities) for the proper spacing.

+ Figure 1 is too large on page 5 and could be reduced to 65% of it's size. It is shockingly large compared to the caption text below. Note that figure resizing is considered an unacceptable proof request in their annotation guidelines, but that seems silly to me.

+ Dongbo's ORCID is missing. It should be

    https://github.com/greenelab/meta-review/blob/a0c392bb2c48c69bbaafc5aa4640d64672c005e3/content/metadata.yaml#L97

+ They have odd capitalization on the page 1 metadata, such as "ISRAEL" in Editor and "PLoS" in citation (publisher has been PLOS for many years now).

**Comment by agitter** [comment]
Thanks for these comments @dhimmel.  I'll add them to the PDF annotations I finish today.

> hyperlinks on text that is not a URL have been removed

Do you think I should annotate each instance with the URL that should be linked?  Their style appears to allow parenthetical URLs but not hyperlinked text.  Do we want to add URLs after each instance of hyperlinked text as a compromise?  This would add important linked information but disrupt the flow of the text.

> Hyperlinks in the data availability statement have been removed

I'll reformat this to use "at" based on their presumed hyperlink policy.  For Software Heritage, I think we can remove the identifier if we have the URL written out.

> DOI URLs were omitted for some references

I'll add these back and see what happens.  It may be a policy rather than a mistake.  I'm surprised they left the DOI URL for reference 97.

> They have odd capitalization on the page 1 metadata

I don't understand or agree with it, but this is their house style for this metadata.  All recently published articles are capitalized this way.

**Comment by dhimmel** [comment]
> Do you think I should annotate each instance with the URL that should be linked?

Probably that is best at this point, although regrettable that we must handle this in a manual fashion. I am not so sure that their style or software forbids hyperlinked text, but just that hyperlinks get stripped by their automated pipeline and that URLs/DOIs get new hyperlinks generated. So I think it makes sense to request that the text is hyperlinked. If we really do have to list out URLs separately that will get quite ugly.

> I'll reformat this to use "at" based on their presumed hyperlink policy. For Software Heritage, I think we can remove the identifier if we have the URL written out.

I think this makes sense. It is likely that the data availability statement has less advanced formatting options than the main text. Therefore, I could see where the data availability statement cannot have hyperlinked text, but the main text can.

> I'll add these back and see what happens. It may be a policy rather than a mistake. I'm surprised they left the DOI URL for reference 97.

It makes no sense to omit the DOI (along with the URL) for things that have a DOI, so I am guessing they just haven't properly considered how to treat non-journal articles with DOIs, and that they will happily add back DOI URLs.

**Comment by dhimmel** [comment]
Looks like the uncorrected proof is now live at https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007128. The DOI URL hasn't been registered yet, but should start working soon https://doi.org/10.1371/journal.pcbi.1007128. It will probably be easier to review the HTML version than the proof PDF. Perhaps we could even create an automated diff to help catch any production errors.

Update: DOI is activated. ShortDOI URL is https://doi.org/c7np

**Comment by agitter** [comment]
During my review of the PDF, I've noticed many locations where adding a parenthetical URL will cause formatting problems or disrupt the flow of the text.  Table 2 is one such example.  I'm currently planning to add a general request to restore the hyperlinked text and also selectively add parenthetical URLs where they fit and are especially important.  I'll upload my proofs later today so that you can see what I identified as important URLs.

**Comment by agitter** [comment]
Here is my annotated proofs PDF.  @dhimmel I believe I captured everything you noted above, except the odd metadata capitalization they use on the first page.  I would like to submit this to the journal by late-morning on Tuesday so please let me know if you find any mistakes.
[pcbi.1007128-annotated.pdf](https://github.com/greenelab/meta-review/files/3322710/pcbi.1007128-annotated.pdf)

I manually added parenthetical URLs, using my best judgement to decide which needed to be omitted or were not essential.  I copied almost all of the URLs.  I'll still request the editors hyperlink the text instead per my statement below.

The DOI link for reference 48 was wrong, probably because our original manual references have the wrong DOI:
https://github.com/greenelab/meta-review/blob/a0c392bb2c48c69bbaafc5aa4640d64672c005e3/content/manual-references.json#L67

I fixed this in the proofs for now.  We should also fix the source later.

Despite these formatting issues, it's great to see the uncorrected version live at PLOS Comp Bio.  I'll likely broadcast the publication after submitting the proofs.

Here is the statement I'll add along with the annotated PDF.  Suggestions are welcome.
> In several locations throughout the text, code formatting and hyperlinks were removed.  The code formatting is essential to demonstrate how the Manubot software can be used.  The hyperlinks are important to give credit to software dependencies and to link to specific documents that illustrate the points made in the manuscript.  Removing these links changes the scientific content of this software article.  We strongly prefer to restore the hyperlinks directly on the text as in the original submission.  As a backup, we have added some of the most essential URLs as PDF annotations if direct hyperlinks are not possible.  These parenthetical URLs are not needed if the hyperlinked text can be restored.

> The HTML version of the original submission at https://greenelab.github.io/meta-review/v/a0c392bb2c48c69bbaafc5aa4640d64672c005e3/ shows the desired hyperlinks in the text.  The citation utilities section at https://greenelab.github.io/meta-review/v/a0c392bb2c48c69bbaafc5aa4640d64672c005e3/#citation-utilities shows the proper code formatting for that example.

> Author Dongbo Hu should also have an ORCID icon and link to http://orcid.org/0000-0003-2606-3969

> The terms "web page" and "webpage" are used inconsistently and should be changed to match, preferably using "webpage".

> Because hyperlinked text was removed in the Data Availability Statement, please update the statement to the following:
The source code and data for this manuscript are available at https://github.com/greenelab/meta-review and archived via Software Heritage at https://archive.softwareheritage.org/swh:1:dir:da789e842d0af90f0fa50de522f0c4caae95e4e3;origin=https://github.com/greenelab/meta-review/. Source code for Manubot resides in the following repositories: https://github.com/manubot/manubot (GitLab mirror at https://gitlab.com/manubot/manubot, archived at https://archive.softwareheritage.org/swh:1:dir:506058af283d6d311a92d03b02adb9dca9f139de;origin=https://github.com/manubot/manubot.git/, packaged on PyPI at https://pypi.org/project/manubot/) and https://github.com/manubot/rootstock (GitLab mirror at https://gitlab.com/manubot/rootstock, archived at https://archive.softwareheritage.org/swh:1:dir:4e689f4e2f4b272b8672142f4c81abd3e77392f9;origin=https://github.com/manubot/rootstock.git/).

**Comment by dhimmel** [comment]
@agitter thanks for the quick turnaround on the proof! Note looks good.

If we want to simplify the data availability statement, it's probably okay to remove the following part of the URL: `;origin=https://github.com/greenelab/meta-review/`

Annotations on the PDF look good. I didn't see a note with Dongbo's ORCID, but that could be due to my PDF viewer lacking some capabilities.

**Comment by agitter** [comment]
> If we want to simplify the data availability statement

I prefer the long version with the `origin` because then Software Heritage adds more information, like the releases, different visits, and a link back to the original repo.  @dhimmel are you okay to leave it?

> I didn't see a note with Dongbo's ORCID

I have a small note after his author name in the PDF and will also add it to the note above (edited).  Some journals tie ORCID links to the author's information in their account in the submission system.  I'm not sure whether that's the case here.

If there are no other changes, I'll upload this after we decide on the Software Heritage links.

**Comment by dhimmel** [comment]
> I prefer the long version with the origin because then Software Heritage adds more information, like the releases, different visits, and a link back to the original repo. @dhimmel are you okay to leave it?

Not a problem. Go ahead and submit.

Amazing [tweet storm](https://twitter.com/anthonygitter/status/1143540432808423426) BTW.

**Comment by slochower** [comment]
Thanks for your work @dhimmel and @agitter on the proofs. Congratulations all!

**Comment by agitter** [comment]
I submitted the corrected proofs.

**Comment by agitter** [comment]
Version 2 of the manuscript is now available at PLOS Computational Biology. I'll work on confirming all of the requested changes were made.

**Comment by dhimmel** [comment]
> I'll work on confirming all of the requested changes were made.

The diff of `plos-comp-bio/outputs/journal.pcbi.1007128.xml` in https://github.com/greenelab/meta-review/pull/252 may be helpful.

Looks like as of [version 2](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007128&rev=2) hyperlinks were inserted as URLs (rather than hyperlinking the text). This leads to some ugly sections, but is better than not having the links at all:

> ![image](https://user-images.githubusercontent.com/1117703/60914899-8133fb00-a258-11e9-8c93-6abae70ff168.png)

Compare this the [Manubot display](https://greenelab.github.io/meta-review/v/9e918275ba33e726a281466c0df94ce45e740d7e/#existing-manuscripts) / our submitted document:

> ![image](https://user-images.githubusercontent.com/1117703/60914989-b80a1100-a258-11e9-93b8-fdd3e2649a32.png)

The formatting of the code block has been improved slightly, but there are still major issues:

> ![image](https://user-images.githubusercontent.com/1117703/60915054-e4259200-a258-11e9-9f02-19a2fe3a9fe0.png)

It appears that each line has been wrapped in an HTML paragraph element. @agitter will leave it up to you whether we want to continue pursuing fixes to these issues.

**Comment by agitter** [comment]
I went through the version 2 diff and noted these requests made on the proofs there were not implemented:
- Dongbo's ORCID link http://orcid.org/0000-0003-2606-3969 is missing 
- "web page" not changed to "webpage" in abstract and introduction
- They did not resize Figure 1
- Table 2 caption "doi:10.7554/eLife.38532" missing "doi:"
- "at https://greenelab.github.io/scihub-manuscript/v/8fcd0cd665f6fb5f39bed7e26b940aa27d4770ba/" was supposed to be inside parenthesis
- `manubot cite` syntax still broken (see above)
- Didn't change "their" to "his" in acknowledgements
- Left the double arXiv in the arXiv references

Some of these I'm okay with.  I'll write the journal about the rest and see if they're willing to make changes.  Fortunately, they seem to have copied the dozens of new links into the text correctly.  They are ugly, but at least the important content is there.

**Comment by agitter** [comment]
PLOS responded to the minor changes I requested:

> Thank you for alerting us to these issues. Unfortunately, we are unable to change any details of the published version. Therefore, there are two options at this point: you can either add this text as an update to the article yourselves, using our Commenting feature, or we can process it as a Formal Correction.

> Formal Corrections generally point out significant problems that affect the understanding of your article or its associated metadata, and are published as a separate article that is then linked to your original published article.
You can see an example of a Formal Correction here:
http://www.ploscompbiol.org/article/info%3Adoi%2F10.1371%2Fannotation%2F96a702bd-85a5-49d9-8fcc-3aad7aa4afa7

> Formal Corrections are also sent to PubMed and thus should remain attached to all versions of your article. See our Corrections policy here: http://www.ploscompbiol.org/static/policies#corrections

> Whether a note added by you, the authors, or a Formal Correction processed by the journal team is more appropriate depends on whether you feel that the change is integral to or alters the scientific meaning or understanding of this paper.

> Please email us letting us know whether you would consider this to merit a Formal Correction or a clarification note added by you.

These changes don't require a formal correction.  @dhimmel should I add an author comment stating that https://greenelab.github.io/meta-review/ has minor updates and post-publication formatting corrections?

**Comment by dhimmel** [comment]
> should I add an author comment stating that https://greenelab.github.io/meta-review/ has minor updates and post-publication formatting corrections?

I think that's a good idea. You could also link to this issue regarding the formatting issues. This issue is a strong example of how preventing a journal from introducing errors into a manuscript can be an impossible task, even with the most vigilant and communicative authors.

**Comment by agitter** [comment]
I added the [article comment](https://journals.plos.org/ploscompbiol/article/comment?id=10.1371/annotation/17cdbd60-801d-4b90-b091-a76906768ad0):
> Please see the Manubot version of this manuscript at `https://greenelab.github.io/meta-review/` for minor post-publication updates.  These include formatting corrections that are detailed in `https://github.com/greenelab/meta-review/issues/246`.
