### ISSUE TITLE
Related tools and workflows

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#249]
@nichtich thanks for pointing us to these relevant tools and workflows.  We'll do some research and discuss them here (the repository for the Manubot manuscript).  We can then update the manuscript as needed.

Per https://twitter.com/nichtich/status/1143622594404474880:
> Looks a lot like my Pandoc + wcite/citation-js + http://hypothes.is  workflow. I'm surprised the authors don't mention/know larswillighagen's citation-js. Another related (but more different) framework is csarven's dokieli.

The related projects:
- https://citation.js.org/
- https://dokie.li/
- https://www.npmjs.com/package/wcite and https://www.npmjs.com/package/wcite#filter-pwcite

Do you have an example of the "Pandoc + wcite/citation-js + http://hypothes.is workflow" you can share?

**Comment by dhimmel** [comment]
Thanks for sharing these tools. I think I may have seen the [Citation.js preprint](https://doi.org/10.7287/peerj.preprints.27466v1 "Citation.js: a format-independent, modular bibliography tool for the browser and command line") but perhaps incorrectly conflated it with [citeproc.js](https://github.com/Juris-M/citeproc-js). It does look like Citation.js is more focused on citation-by-identifier and that we should familiarize ourselves with it.

I have played around with https://dokie.li/ a few times and it never clicked, but I'll give it another look.

**Comment by csarven** [comment]
There is a peer-reviewed article at http://csarven.ca/dokieli-rww that you might find useful. For most up to date documentation on dokieli's features and the specifications it uses, see https://github.com/linkeddata/dokieli (and potentially https://dokie.li/docs as the canonical location for the documentation but note that it wasn't updated recently.) For general questions, you're welcome to join the public chat at https://gitter.im/linkeddata/dokieli . I can share my thesis soon if interested in a more comprehensive description of dokieli and the ecosystem.

**Comment by larsgw** [comment]
> I think I may have seen the Citation.js preprint but perhaps incorrectly conflated it with citeproc.js.

(I'm working on updating the preprint soon.)

> It does look like Citation.js is more focused on citation-by-identifier and that we should familiarize ourselves with it.

Yep, and citation-by-file too but the extent of that isn't great yet, only BibTeX (and [CFF](https://citation-file-format.github.io/) with non-default plugins). Links: [GitHub](https://github.com/larsgw/citation.js), [docs](https://citation.js.org/api), [blog](https://citation.js.org/blog/) and [chatting space](https://gitter.im/citation-js/Lobby).

**Comment by agitter** [comment]
I read the Citation.js preprint (January 5, 2019 version) to see how it relates to Manubot and this meta review manuscript.  Overall, Citation.js is a very nice modular citation utility.  It can parse and process citations from multiple input formats (see table below) or retrieve reference metadata from persistent identifiers.  Currently, Wikidata and DOIs are the supported ids.  Because it is JavaScript-based, there are lots of cool applications like the [Citation.js Replacer](https://citation-js.github.io/replacer/) as well as a command line interface.

Table 1 from https://peerj.com/preprints/27466/?td=bl
![image](https://user-images.githubusercontent.com/3532898/61057114-40ec8e00-a3ba-11e9-8f01-7e99bc0716ae.png)

The meta review does not cover general citation management or bibliographic tools, so I do not think we want to discuss those aspects of Citation.js.  The most relevant part for us is the integrations section
![image](https://user-images.githubusercontent.com/3532898/61057406-e273df80-a3ba-11e9-9b00-611821130ddb.png)

We could reference the [Citation.js showdown](https://github.com/larsgw/citation.js-showdown) extension.  The simple [test case](https://github.com/larsgw/citation.js-showdown/tree/master/test) gives a sense of how it works, converting Wikidata identifiers in the Markdown to references in the HTML.

[ReLaXed ](https://github.com/RelaxedJS/ReLaXed) is also relevant, but I am still looking for an example document that uses the Citation.js integration.
> ReLaXed creates PDF documents interactively using HTML or Pug (a shorthand for HTML).

@larsgw does that seem accurate?

**Comment by csarven** [comment]
As mentioned before and hopefully still to interest to the folks here, the thesis:
[Linked Research on the Decentralised Web](https://csarven.ca/linked-research-decentralised-web)

**Comment by larsgw** [comment]
@agitter sorry for the delay, I was attending the International Biology Olympiad. A new version of the preprint got published 11 July, with some more background and explanation. Regarding Table 1, there is more stuff available ([roadmap](https://github.com/orgs/citation-js/projects/1)) as of late: [CFF](https://github.com/citation-js/plugin-software-formats), [ISBN](https://github.com/citation-js/plugin-isbn) and [ORCID](https://github.com/citation-js/plugin-orcid), and I'm working on RIS input.

> We could reference the Citation.js showdown extension. The simple test case gives a sense of how it works, converting Wikidata identifiers in the Markdown to references in the HTML.

The showdown extension was developed for an older version of Citation.js, but I could update it if needed. In the new version of the preprint, Table 3 has a number of other uses found in the wild.

> ReLaXed is also relevant, but I am still looking for an example document that uses the Citation.js integration.

They moved the Citation.js integration to a [separate repo](https://github.com/RelaxedJS/relaxed-citationjs), there's a sample document [there](https://github.com/RelaxedJS/relaxed-citationjs/blob/master/test/samples/pug/basic_citationjs_example/master.pug).
