### ISSUE TITLE
References to existing collaborative writing projects and reviews

### ISSUE THREAD

**Issue by dhimmel** [greenelab/meta-review#25]
It dawned on me that Wikipedia is quite similar to a collaboratively written review. For example, we could have made a page titled "Precision medicine in deep learning". Wikipedia is more removed from academia, but we should consider a mention and a few references on its power versus pitfalls.

As far as more traditional academic review articles written collaboratively, I think [A multi-disciplinary perspective on emergent and future innovations in peer review](https://doi.org/10.12688/f1000research.12037.2) fits the bill. @Protohedgehog can you confirm that this article was written collaboratively online and if so how? Is there a homepage for contributing?

**Comment by Protohedgehog** [comment]
Hey Dan,

So, yeah, Wikipedia is a special case of collaborative authoring. If you see Section 3.5 of the paper you mention (read only link to current version on Overleaf: https://www.overleaf.com/read/bfczqxwyhykk), you can see some discussion and examples of how this happens.

So, yeah, for this paper, and a previous one (https://f1000research.com/articles/5-632/v3) we used a similar authoring model. Basically, I started drafting a paper online using Overleaf. Then, on social media, I would share the read and edit link to that draft, as well as directly with people I knew the paper would be of interest to. The policy was that anyone could contribute, and if they felt their contribution constituted co-authorship, they could add themselves. Many more left comments, or offered discussion points off the platform. The whole paper was written in an iterative process of collaboration, with myself I guess as a sort of 'senior editor'. You can track all input from authors on the platform too - good for verifying contributions and that authors haven't just randomly added themselves.

It's not systematic, but it's about as comprehensive as it gets, as you have so many eyes on it at all times. Peer review still found some issues with it, as did the comments, as expected. But essentially, this is a crowd-sourced paper, written in the open with a collaborative writing platform. It was a pretty awesome process!

**Comment by dhimmel** [comment]
@Protohedgehog thanks for the info. We'll make sure to reference these projects in our [Meta Review](https://greenelab.github.io/meta-review/) (still a work in progress) and will ping you with any other questions we have about your setup!

**Comment by Protohedgehog** [comment]
Alright, sweet! I'm at your disposal. If you happen to be in Berlin next week for certain things, you know where to find me!

**Comment by agitter** [comment]
@dhimmel we're currently citing the peer review paper for its discussion of open review and review on GitHub.  We should definitely mention it again as a collaborative writing example.

**Comment by dhimmel** [comment]
# The HoTT book

I just learned about the HoTT Book completed in 2013. From this [blog post](http://math.andrej.com/2013/06/20/the-hott-book/):

> We are a group of two dozen mathematicians who wrote a 600 page book in less than half a year. This is quite amazing, since mathematicians do not normally work together in large groups. In a small group they can get away with using obsolete technology, such as sending each other source LaTeX files by email, but with two dozen people even Dropbox or any other file synchronization system would have failed miserably. Luckily, many of us are computer scientists disguised as mathematicians, so we knew how to tackle the logistics. We used git and github.com. In the beginning it took some convincing and getting used to, although it was not too bad. In the end the repository served not only as an archive for our files, but also as a central hub for planning and discussions.

The GitHub is https://github.com/HoTT/book and there's a webpage for the book at https://homotopytypetheory.org/book/.

Cool!

**Comment by agitter** [comment]
This is a great example!  We should cite it.  At a glance, they used issues, pull request, and reviews in a similar manner to deep review.

**Comment by agitter** [comment]
Another collaborative paper (via Google Docs) described [here](http://www.sciencemag.org/news/2018/01/nearly-100-scientists-spent-2-months-google-docs-redefine-p-value-here-s-what-they-came) `10.1126/science.aat0471`. 

https://doi.org/10.1038/s41562-018-0311-x
https://doi.org/10.17605/OSF.IO/9S3Y6

**Comment by dhimmel** [comment]
https://github.com/bitcoinbook/bitcoinbook
https://github.com/ethereumbook/ethereumbook
