### ISSUE TITLE
Ten simple rules for researchers collaborating on Massively Open Online Papers (MOOPs)

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#250]
Ten simple rules for researchers collaborating on Massively Open Online Papers (MOOPs)
https://doi.org/10.31222/osf.io/et8ak

> An enormous wealth of digital tools now exists for collaborating on scholarly research projects. In particular, it is now possible to collaboratively author research articles in an openly participatory and dynamic format. Here we describe and provide recommendations for a more open process of collaboration, and discuss the potential issues and pitfalls that come with managing large and diverse authoring communities. We summarize our personal experiences in a form of ‘ten simple rules’. Typically, these collaborative, online projects lead to the production of what we here identify as Massively Open Online Papers (MOOPs). We consider a MOOP to be distinct from a ‘traditional’ collaborative article in that it is defined by an openly participatory process, not bound within the constraints of a predefined contributors list. This is a method of organised creativity designed for the efficient generation and capture of ideas in order to produce new knowledge. Given the diversity of potential authors and projects that can be brought into this process, we do not expect that these tips will address every possible project. Rather, these tips are based on our own experiences and will be useful when different groups and communities can uptake different elements into their own workflows. We believe that creating inclusive, interdisciplinary, and dynamic environments is ultimately good for science, providing a way to exchange knowledge and ideas as a community. We hope that these rules will prove useful for others who might wish to explore this space.

This paper is relevant and could be discussed during our next round of revisions..

**Comment by dhimmel** [comment]
The section of the review mentioning Manubot is:

> Next to the above mentioned editor-focused solutions, GitHub and GitLab can also be used for collaborative authoring. As a noteworthy example of how textual collaboration in scholarly communication with Git[Hub] works, see the The Journal of Open Source Software (JOSS). Further to that, and similarly building on a distinctly GitHub-based workflow,  Manubot warrants a mention here: its developers propose a toolchain approach that allows for writing, tracking and converting Markdown-based text into a variety of output formats via a collection of pre-configured tools such as Pandoc (Himmelstein et al. 2019). And while we have not had a chance to try this out in more detail, it might well be an option for those technically-savvy enough to play around with customizing and tweaking their git workflow. Drawing from our own experiences, the development of the Foundations for Open Scholarship Strategydocument ([Tennant et al. 2019](https://doi.org/10/gft5hx)) was primarily authored using the in-built collaborative tools originally designed for software development, and written in Markdown. The final ‘product’ was then easy to transform into a dynamic webpage, and also a preprint (see Rule 10 for more on this).

It may not be a bad idea to reference this paper since it contains other pre-existing MOOPs. Also would be good for us to at least mention the "MOOP" terminology.

In general, we should decide whether we want to continue updating the Meta Review. I'm in favor of updating the Meta Review with any works or citations that were available as of June 24, 2019 (the journal publication date). I'm okay with citing this MOOP paper even though it came afterwards, because it is so relevant. However, I think we may want to limit the types of changes we are willing to make to the Meta Review, unless we are ready to take on a long term maintenance burden.

**Comment by agitter** [comment]
Yes, we should minimize what types of changes we plan to make.  I would support targeted changes such as:
- highly relevant related work we missed (agree with the publication date threshold as a general heuristic)
- updating dead URLs
- potentially new Manubot resources we want to advertise, like a link to the catalog

It could be too much work to update the manuscript to reflect Manubot's current features as it evolves.  Specific changes, like new citation types in Table 2, could be an exception, though I see benefits to letting the manuscript reflect the current snapshot of Manubot.
