### ISSUE TITLE
Update this manuscript's thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/meta-review#257]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![New Project](https://user-images.githubusercontent.com/8326331/64815340-56756400-d573-11e9-8049-01d8e4f992cc.png)

OR

![New Project (1)](https://user-images.githubusercontent.com/8326331/64815489-b0762980-d573-11e9-8c96-256ebdea7dce.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by dhimmel** [comment]
Cool logo! Wow. I like the pencil and manubot logo one.

**Comment by dhimmel** [comment]
Is a vector version of the pencil-M available as well? I imagine that would be good to have on hand.

**Comment by vincerubinetti** [comment]
I think it's on my work computer. Also I just noticed that there was some slight opacity issue there. I'll probably remake it and rework it a bit on Monday. Maybe add a shadow or something.

If you want to play around with it, it's just the pencil icon from font awesome icon. And then the Manubot logo rotated and skewed a bit.
