### ISSUE TITLE
Overleaf

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#27]
I started using Overleaf for a project, and we may need to update our discussion of it in this manuscript.  I'll learn more over the next few days, but it appears to have fairly good git support.  I can see the git log, and the commits are anonymous if made directly on the Overleaf website without signing in or associated with the user name and email if made when logged it.

```
$ git log
commit 301be8a43d1dce8fcd0f6ca74536d6e6ac59247d
Author: Anthony Gitter <gitter@biostat.wisc.edu>
Date:   Fri Dec 8 16:50:46 2017 +0000

    Update on Overleaf.

commit f5ade6680506b5ad49530633983e34c52fc13ee9
Author: Anonymous <anonymous@overleaf.com>
Date:   Fri Dec 8 16:05:16 2017 +0000

    Update on Overleaf.
```

**Comment by dhimmel** [comment]
That's nice that Overleaf maintains an underlying git repo.

The differences with Manubot (correct me if I'm wrong):

+ With Manubot you get to apply the open source software development model to modifying the manuscript. Does Overleaf support something analogous to a fork/branch and a corresponding pull request? From the [Overleaf blog](https://www.overleaf.com/blog/195-new-collaborate-online-and-offline-with-overleaf-and-git-beta) on git support:

  > you can only push changes to the master branch on Overleaf.

+ Manubot is customizable. Overleaf is only as customazable as overleaf.com makes it.

+ Overleaf is LaTeX based, with [some hacks](https://www.overleaf.com/blog/441-how-to-write-in-markdown-on-overleaf) allowing writing in markdown. The bibliography still has to be in the outdated bibtex format?

+ Manubot has additional features like citation metadata fetching and templating.

**Comment by agitter** [comment]
Your list seems correct to me thus far, though I still haven't done much with Overleaf.  The software development approach is a huge difference that we may want to emphasize even more in the meta review.  It looks like Overleaf supports comments on the manuscript, but I can't image coordinating and writing the deep review with comments alone for author communication, organization, and feedback.

**Comment by agitter** [comment]
I haven't confirmed this, but I believe that if multiple authors are editing at the same time then their edits can all be associated with the same git commit with a single author.  We could easily create a test document to confirm this if it is important for our discussion.

**Comment by agitter** [comment]
Issue #44 subsumes this issue.

**Comment by agitter** [comment]
I finally found [documentation](https://www.overleaf.com/help/230-how-do-i-push-a-new-project-to-overleaf-via-git#.W1jhM9JKiUk) on Overleaf that supports what I had observed about the git commit behavior:
> At present the online edits aren't saved in the git logs every time you make an edit online. The git bridge works this way: when we get a pull or fetch request, the git bridge copies the latest content from Overleaf to a git repo maintained by the git bridge, and then we commit it. In other words, a git commit is generated whenever a user git-pulls or fetches from the project. If you save a version via the History and Revisions menu, and then you do a git pull, the saved version will become a commit in the repository’s git history.

This is how edits from multiple users can be rolled into a single git commit attributed to a single user.

**Comment by dhimmel** [comment]
# Overleaf v2

Overleaf and ShareLaTeX merged. It sounds like the new product keeps the Overleaf name but the ShareLaTeX technology, as per the [launch announcement](https://www.overleaf.com/blog/654-overleaf-v2-launch-announcement):

> For ShareLaTeX users, Overleaf v2 should feel familiar because it is built on the same underlying ShareLaTeX technology.

There is an interesting bullet point on git:

> **Git users in Overleaf:** If you use the Git-bridge in Overleaf, you will need to continue to use Overleaf v1 until the end of the year, when we will bring the Git-bridge into Overleaf v2.

If you've used the new overleaf v2 and have any feedback (especially related to it's comparison to Manubot), leave it here and perhaps at some point we can update the table to apply to v2.

**Comment by agitter** [comment]
I'm using Overleaf v2 for a manuscript.  My workflow is different in v2 because I used to rely on the git bridge, but I may prefer the v2 model. Overleaf v2 can sync with a public or private GitHub repo so locally cloning that GitHub repo enables you to still get a local copy of the repo.

A downside of v2 is the that commit authorship has gotten even less granular as far as I can tell.  Now all commits are authored by the project owner when I sync to GitHub to view them.  For a collaborative project one could make the commits locally, review and merge them in GitHub, and sync with Overleaf.  But then Overleaf would be reduced to a LaTeX rendering service.

Because v2 is still changing, we'll need to log a datestamp again if we add it to the table.

**Comment by agitter** [comment]
The Open Humans project has a blog post describing writing an open paper with Overleaf: http://openhumansfoundation.org/open-humans-manuscript/

My impression is that our existing understanding of Overleaf v2 is accurate.  They appear to have give everyone write permission.  They have synced to a GitHub [repository](https://github.com/OpenHumans/open-humans-manuscript) (also used for that blog post) but are not actively using it to track changes (currently 3 commits).

**Comment by agitter** [comment]
Overleaf v2 now has a beta version of the git bridge that allows syncing directly to the Overleaf project instead of syncing Overleaf v2 <-> GitHub and GitHub <-> local repo.

https://www.overleaf.com/blog/bringing-the-git-bridge-to-v2-its-here-in-beta

**Comment by agitter** [comment]
> A downside of v2 is the that commit authorship has gotten even less granular as far as I can tell.

This is no longer true for Overleaf v2.  I tested using Overleaf v2 as a git remote (as opposed to GitHub sync) and it correctly set me as the commit author.  This was on a project I did not own.  I haven't tested this broadly though.
