### ISSUE TITLE
Bitcoin section may not be ideal for a general audience.

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#32]
In #26 @agitter noted that the bitcoin/blockchain section may not be interpretable to a general audience. I can take a stab at revising this section after #26 is merged.

**Comment by agitter** [comment]
In addition to making the last couple lines of the timestamping paragraph accessible to a general audience, I suggest we cite https://petertodd.org/2016/opentimestamps-announcement.  This was a huge help for me to understand what the `ots` client is doing.
