### ISSUE TITLE
CDF of Deep-Review reference list

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#36]
It might be nice to highlight some of the items that the programmatic DOI collection gives us. We could implement this (suggested by @michaelmhoffman) to show off some of that:
https://twitter.com/michaelhoffman/status/966051493211127808

**Comment by agitter** [comment]
Visualizing the reference counts over time should be feasible for the more recent versions of deep review.  At some point, Manubot started storing these in one of the [output JSON files](
https://github.com/greenelab/deep-review/blob/adbf7807d68e15a7742ab5beb1d754326c1d9261/variables.json#L618-L625)
```
  "manuscript_stats": {
    "reference_counts": {
      "arxiv": 129,
      "doi": 369,
      "pmcid": 6,
      "url": 48,
      "total": 552
    },
```

**Comment by michaelmhoffman** [comment]
The idea is a plot of publication dates for the references, not date the reference was added to the review.

**Comment by agitter** [comment]
Focused on only the publications that are cited in deep review or a more general scrape of relevant articles over time like [this review](https://arxiv.org/abs/1603.06430)?
![image](https://user-images.githubusercontent.com/3532898/36452789-6d40621c-165b-11e8-9995-f7d742e62255.png)

I'm assuming the former.

**Comment by michaelmhoffman** [comment]
I meant the former, and also daily or monthly counts, not annual.

**Comment by dhimmel** [comment]
I am going to close this as I don't think it's on the roadmap currently for the Meta Review. If someone is interested in this, they can perform the analysis elsewhere.
