### ISSUE TITLE
Update Manubot 

### ISSUE THREAD

**Issue by dhimmel** [greenelab/meta-review#4]
@agitter we should merge in the latest changes from manubot-rootstock.

I've done this process several times and don't find it too difficult. But if you would like to try for experience, go ahead. We could also video chat or something, so I could walk you though the process.

The merge commit will look something like https://github.com/greenelab/scihub-manuscript/commit/9402260dbcfdd5b7d716b6badb84405d60e4d79a

**Comment by agitter** [comment]
@dhimmel If you don't mind, I'd prefer to have you do it.  Even if the merge isn't too complicated, my time to work on this has been limited so I'd like to focus on drafting the discussion next.
