### ISSUE TITLE
Make github workflow figure

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#40]
#8 has some parts about PR commenting. This would be more general. I'll start with a sketch and then we can discuss improvements.

**Comment by cgreene** [comment]
![img_20180614_111521](https://user-images.githubusercontent.com/542643/41426583-16212fc2-6fd2-11e8-9a66-0c2d7809a0ac.jpg)
I drew this on a whiteboard. After conversation with @agitter and @dhimmel we agreed to move forward with making something like this.

**Comment by cgreene** [comment]
I used google draw to create this. Version 1.0.0 is here. Feel free to edit: https://docs.google.com/drawings/d/17mst0Z1RMXegeGhM6SwQSJ4nhHgMMh5csyV4MwhsgAY/edit
![process-figure](https://user-images.githubusercontent.com/542643/41426626-3b29fa10-6fd2-11e8-938d-44e3b19cd1af.png)

**Comment by cgreene** [comment]
Slight update in the google doc (not reflected here) to remove the extra box around the checkmark.

**Comment by dhimmel** [comment]
Nice! Not sure I understand what qualifies lines as being colored/dashed.

**Comment by agitter** [comment]
That looks great.  I moved `Document` to center it above the rectangles.

Do we want the circle and arrow coming from the main branch to the Discussion column?  I interpret the circles as git commits, but that may not be the intention.

**Comment by cgreene** [comment]
I was trying to make the circles on the arrows as git commits. I was trying to make the circles associated with comments an indicator of who was saying them. However, in retrospect, maybe most of these can be removed.

Colored arrows are: someone has made a change to the document in the repository.

Colored squiggles are text written by the person matching the color.

**Comment by agitter** [comment]
I like the colored circles.  My confusion was only the black circle that creates an issue.

**Comment by cgreene** [comment]
Whoops! Yes - that should not have a circle there. And there should be one where the green arrow comes back in.

**Comment by cgreene** [comment]
Another question - what color should the circle be at that stage? Purple or black?

**Comment by cgreene** [comment]
I went with purple. I think it more clearly notes that the version contains the changes proposed by the purple contributor.

**Comment by cgreene** [comment]
This is also a squash-merge situation unless we add another dot between the two edits from the purple contributor.

**Comment by agitter** [comment]
I like this version.  If we have colors for some of the lines and arrows, should we color more of them?  Or make all lines and arrows black and let the circles, text, and squiggles denote who took what action?

**Comment by cgreene** [comment]
I'm happy to make all of the arrows black. The one I really cared about when I made it was the bottom dotted arrow, to show that the purple contributor was making that change in response to the orange participant. I also made the one above to show that the purple contributor makes the PR to suggest the change, but I care less about that.

**Comment by agitter** [comment]
I have a slight preference for all black arrows.  It keeps me focused on the colors that matter the most.

@dhimmel what do you think?

**Comment by cgreene** [comment]
I made all the arrows black. It is easy to change back if desired.

**Comment by cgreene** [comment]
![process-figure 1](https://user-images.githubusercontent.com/542643/41430906-51d2c08c-6fdf-11e8-9f57-fd0f9ba22fc8.png)

This is version 1.0.1 (current)

**Comment by dhimmel** [comment]
I really like this. I made the Document / Discussion headers font size 16 (previousely 14), so that they would stick out a bit more. Still not thrilled by them... it's not super obvious that they delineate the two sides, but may be hard to improve.

Next step would be add to the manuscript and create a legend.

**Comment by agitter** [comment]
I changed the canvas size and created version 1.0.2.

**Comment by cgreene** [comment]
I bolded the "Document" and "Discussion" headers and fixed the alignment of the actions on the right hand side. Now labeled 1.0.3
