### ISSUE TITLE
Identify specific deep review example

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#41]
We want a contribution from reader identifies change -> file issue & discuss -> file PR & discuss -> final revisions to PR -> final merging.

@agitter do you want to come up with one of these examples that you particularly like as an exemplar workflow?

**Comment by agitter** [comment]
One option: protein-protein interactions:
- Issues https://github.com/greenelab/deep-review/issues/575 and https://github.com/greenelab/deep-review/issues/689
- Pull request https://github.com/greenelab/deep-review/pull/638

A downside of this example is that it took a long time to review and merge the pull request.

**Comment by cgreene** [comment]
I think this is ideal. It did take a long time to merge, but it did get merged and it even shows a new contributor to the project. 👍

**Comment by agitter** [comment]
It matches the workflow in #40 closely as well.  Where were we going to add this in the text?
