### ISSUE TITLE
Paragraph describing Manubot usage

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#45]
Describe other projects that have used it.

**Comment by agitter** [comment]
See https://github.com/greenelab/manubot-rootstock/issues/67 and https://github.com/greenelab/manubot-rootstock/blob/master/USAGE.md#examples

**Comment by agitter** [comment]
TODOs in the manuscript also noted https://slochower.github.io/nonequilibrium-barrier/ and https://zietzm.github.io/Vagelos2017/.

**Comment by vsmalladi** [comment]
Also add [https://vsmalladi.github.io/tfsee-manuscript/](https://vsmalladi.github.io/tfsee-manuscript/) examples.
