### ISSUE TITLE
Re-run Fig 1 up to V1.0 tag (March 6).

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#51]

**Comment by agitter** [comment]
Brett's name is truncated in the `deep-review-contribution.*` images.  We're not using them so it isn't critical to fix this when we rerun.

**Comment by dhimmel** [comment]
Okay I will fast forward the deep-review submodule to https://github.com/greenelab/deep-review/commit/63d2468883ea69ad7ad638c39efab0fcbe026298, which is the last commit on 2018-03-06.

**Comment by dhimmel** [comment]
Actually https://github.com/greenelab/deep-review/commit/63d2468883ea69ad7ad638c39efab0fcbe026298 which has the [v1.0 tag](https://github.com/greenelab/deep-review/releases/tag/v1.0)

**Comment by agitter** [comment]
Do multiple commits show the `v1.0` tag?
- https://github.com/greenelab/deep-review/commit/63d2468883ea69ad7ad638c39efab0fcbe026298
- https://github.com/greenelab/deep-review/commit/9c2d9c26b8fd40c321a80b854e2e74677cd38c79
- https://github.com/greenelab/deep-review/commit/fafc92abf2716166060a22a3bc60d123011d3e5f

**Comment by agitter** [comment]
The `v1.0` tag symbol might show up for all commits that came after `v0.10` up to `v1.0`.

**Comment by dhimmel** [comment]
@agitter yeah, I'm cunfused. I think https://github.com/greenelab/deep-review/commit/63d2468883ea69ad7ad638c39efab0fcbe026298 from https://github.com/greenelab/deep-review/releases/tag/v1.0 is correct. Perhaps the tag just means that commit was first released by that tag?

**Comment by agitter** [comment]
Yes, I think so

**Comment by dhimmel** [comment]
> Brett's name is truncated in the deep-review-contribution.* images. We're not using them so it isn't critical to fix this when we rerun.

Fixed in #56
