### ISSUE TITLE
Ping manubot-rootstock contributors to determine if they want to be acknowledged

### ISSUE THREAD

**Issue by cgreene** [greenelab/meta-review#58]
See #50 for the approach we used there. Dividing these into two to avoid e-mail noise.

**Comment by agitter** [comment]
Hello manubot-rootstock contributors. We are writing a manuscript describing how manubot was used to write and coordinate our deep learning review. We would like to acknowledge you by name. Please let us know if you approve and, if so, what name you would like us to use.

@vsmalladi @rgieseke @slochower @adebali @petebachant 

@evancofer already responded https://github.com/greenelab/meta-review/issues/50#issuecomment-397383234, but I'm noting his manubot-rootstock contribution here as well.

**Comment by petebachant** [comment]
My contributions were negligible, so no need for acknowledgment. Thanks for asking though--very cool process!

**Comment by vsmalladi** [comment]
I approve. Please use Venkat S. Malladi.

Let me know if I can help with the manuscript at all.

**Comment by rgieseke** [comment]
Sure, thanks! Please use

Robert Gieseke

**Comment by evancofer** [comment]
Thanks! Name to use is Evan M. Cofer

**Comment by slochower** [comment]
Great, thanks. David R. Slochower.

**Comment by agitter** [comment]
Hello manubot-rootstock beta testers. We are writing a manuscript describing how manubot was used to write and coordinate our deep learning review. We would like to acknowledge you by name for your feedback from OpenCon (https://github.com/greenelab/manubot-rootstock/pull/89). Please let us know if you approve and, if so, what name you would like us to use.

@zambujo @RaoOfPhysics @broadwym @schliebs @Hillea

**Comment by agitter** [comment]
Hello manubot-rootstock and manubot contributors. We are writing a manuscript describing how manubot was used to write and coordinate our deep learning review. We would like to acknowledge you by name for your contributions, suggestions, and discussion. Please let us know if you approve and, if so, what name you would like us to use.

@dsiddy @Miserlou @olgabot @jspauld @mlissner @anseljh @Sieboldianus @lierdakil

**Comment by dsiddy** [comment]
Thanks for your consideration in reaching out, @agitter. It's acknowledgement enough for me. 👌

**Comment by adebali** [comment]
Thanks, Ogun Adebali.

**Comment by lierdakil** [comment]
Thanks, but I really didn't contribute much, so I don't think you need to mention me personally. Mentioning pandoc-crossref would be nice if you're still using it though (IIRC you were using it at some point)

**Comment by RaoOfPhysics** [comment]
Thanks for reaching out, @agitter. :) If you think it is appropriate to do so, I would appreciate the acknowledgement. Please let me know if you're looking for future testing as well!

**Comment by zambujo** [comment]
I also appreciate you reaching out.  My contribution was negligible:  no need to acknowledge me at this point.  Best wishes!

**Comment by Sieboldianus** [comment]
@agitter My contribution was so small, but feel free to acknowledge it. Thanks for managing this repo!

**Comment by anseljh** [comment]
Hi @agitter, I don't even remember what I did, if anything. If you can point me to that, I'd be happy to look at it.

**Comment by Miserlou** [comment]
Hey @agitter - all I did was file a bug report. Maybe in future you can have a weak form of a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) in `CONTRIBUTING.md` so you don't need to ask retroactively.

**Comment by agitter** [comment]
@anseljh this was regarding the discussion about how to cite legal cases in https://github.com/greenelab/manubot/issues/1

**Comment by anseljh** [comment]
Thanks @agitter, I remember that now. Feel free to acknowledge if it was helpful, but I leave it up to you!

**Comment by agitter** [comment]
Closed by #77, but anyone who was pinged above and has not yet been acknowledged should still feel free to respond here.
