### ISSUE TITLE
Developing a modern data workflow for living data

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#63]
https://doi.org/10.1101/344804

Should we include this in our discussion?   Continuous integration for data management has parallels to continuous integration for manuscripts.

**Comment by vsmalladi** [comment]
@agitter I think we should add this reference to the Introduction and refer back to it when expanding on continuous integration #64

**Comment by agitter** [comment]
Sounds good.  Want to make a pull request?

**Comment by vsmalladi** [comment]
Great just made a pull request.
