### ISSUE TITLE
Additional discussion of continuous integration benefits

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#64]
In the continuous publication paragraph, we say
> If this process is error free, the CI service timestamps the manuscript and uploads the output files to the GitHub repository.

We could add a line about some specific benefits of integration testing on the manuscript.  We can automatically detect broken citations or other problems before merging pull requests.

**Comment by dhimmel** [comment]
> We could add a line about some specific benefits of integration testing on the manuscript. We can automatically detect broken citations or other problems before merging pull requests.

Ah yes, this point needs to be made somewhere.

**Comment by agitter** [comment]
I scanned some of the failed deep review builds.  The common errors caught with continuous integration were related to tag typos, non-existent tags, or DOI typos.  Other builds failed due to valid DOIs and perhaps were caused by an intermittent outage.  I also recall some builds failing because of JSON file format errors.

Do we also want to comment on what might be possible with continuous integration in future versions of Manubot?

**Comment by vsmalladi** [comment]
@agitter add pull request #83 to add in the information of tag typos and DOI Typos. 

What were you thinking regarding future testing? I am hesitant to add anything as I could only think of specific journal or manuscript requirements we would want to test (e.g. Number of Figures, Word Count limit).
