### ISSUE TITLE
Organize open science discussion and references

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#66]
In the intro and second discussion paragraph, the references about open science were selected arbitrarily.  The current draft has:
> Openness in research — which includes sharing code, data, and manuscripts — benefits the researchers who practice it [1], their scientific peers, and the public.

> Many others have embraced open science principles and piloted open approaches toward drug discovery [38,39], data management [40–42], and manuscript review [43]. 

We should more explicitly consider what we want to include here and search for other relevant work.

**Comment by agitter** [comment]
There are additional ideas and references for open science in https://doi.org/10.7287/peerj.preprints.2711v3

**Comment by slochower** [comment]
> We should more explicitly consider what we want to include here and search for other relevant work.

I just noticed there's a Wikipedia article on Open Science that lists an Open science taxonomy. One thought is to mention the top-level hierarchy -- open access, open data, open reproducible research, open science evaluation, open science policies, and open science tools -- and then add a sentence or two about particularly interesting examples, like drug discovery or data management.

**Comment by agitter** [comment]
There is some good material here.  The primary sources for the six principles --- http://openscienceasap.org/open-science/ and http://www.know-center.tugraz.at/download_extern/papers/open_science.pdf for the first four --- could be useful for introducing them.

The [Arguments_for_open_science](https://en.wikipedia.org/wiki/Open_science#Arguments_for_open_science) section could also provide good references for our introduction.
