### ISSUE TITLE
Alternative author ordering strategies and contribution tracking

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#68]
In the Authorship section we had a TODO
> In Discussion, present alternative author ordering strategies and literature on contribution in collaborative projects

@dhimmel is there more you would like to say about alternative authorship strategies?  The [Contributor Roles Taxonomy](http://docs.casrai.org/CRediT) would be one point of reference.

**Comment by dhimmel** [comment]
In the longterm, I think being able to go from author to their contributions is the more important thing. For example, contributor role metadata (via the taxonomy) would be a good start. Best would be if you could click an author to highlight all sentences they authored.

Not sure if this futurist stuff belongs in Meta Review, as we haven't implemented it.

**Comment by agitter** [comment]
I consider this to be closed by #177.  Anyone can feel free to reopen if there are more changes they would like it make.
