### ISSUE TITLE
Citing software dependencies

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#76]
https://github.com/greenelab/meta-review/issues/58#issuecomment-398670726 reminded me that we may want to explicitly cite or link other software that Manubot depends on.  Despite the comment, we are not actually using `pandoc-crossref`, right?

**Comment by slochower** [comment]
Correct, but `pandoc-fignos`, `pandoc-eqnos`, and `pandoc-tablenos` are used.

https://github.com/greenelab/meta-review/blob/59442cd3b5417ef45c8dd6477ec6a782495aad4b/build/build.sh#L32-L34

**Comment by vsmalladi** [comment]
+1 @slochower

**Comment by dhimmel** [comment]
I plan to close this with https://github.com/greenelab/meta-review/pull/186, which mentions the `pandoc-xnos` filters. While it's great to give credit to software, I'm not sure there is a more elegant way to actually reference versioned dependencies than our conda `environment.yml`. I think the manuscript now mentions most important dependencies by name.

**Comment by agitter** [comment]
I agree that is sufficient.  My original intent of the issue was also to make sure that we cite manuscripts when they exist, which I believe we have covered.
