### ISSUE TITLE
Distill overview

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#96]
The Distill Update 2018 (http://doi.org/10.23915/distill.00013) has some interesting information about their publishing process.  We currently discuss Distill's focus on interactivity but could also mention their peer review through GitHub issues and use of continuous integration.

**Comment by dhimmel** [comment]
Here is what I think is the most relevant portion. Anthony please format this

> Software Engineering Best Practices for Scientific Publishing

> Over the past year, we’ve also seen several advantages to using software engineering best practices to operate a scientific journal. Every Distill article is housed within a GitHub repository, and peer review is conducted through the issue tracker. We’ve found this setup gives readers greater transparency into the publication process. For instance, readers can see how Gabriel Goh’s momentum article has been updated from when it was first published, step through early development to see the genesis of the article’s ideas, and can read the back-and-forth of the review process. More excitingly, we’ve seen readers engage in on-going, post-publication peer review including sending pull requests to fix typos, making more thorough editing passes, and even sparked discussions with the author.

> Authors also benefit from this setup as Distill provides continuous integration for scientific papers. Prior to publication, draft articles are automatically built and served from password-protected URLs. Authors are free to share these addresses to solicit initial feedback, and can be confident that their readers will always see the most up-to-date version of the draft.

**Comment by agitter** [comment]
I put that in a blockquote to make it obvious that is a quote from the article above.  I'll focus on that section for my edits.

**Comment by agitter** [comment]
I added this article and Distill's use of GitHub in #100.  I left out continuous integration because I don't understand when or where they perform it.  Based on the example repository they link - https://github.com/distillpub/post--momentum - it doesn't seem to be via GitHub.
