### ISSUE TITLE
Revisions before next submission

### ISSUE THREAD

**Issue by agitter** [greenelab/meta-review#97]
- [x] Edit the abstract to de-emphasize literature reviews and emphasize open collaboration and automation
- [x] Discuss the new Manubot features that will be included in the v0.2.0 release
- [x] Prune some of the retrospective deep review discussion to focus more on how others can use Manubot
- [x] Add Kipoi as a Manubot use case

**Comment by agitter** [comment]
I added ` Add Kipoi as a Manubot use case` so that we can briefly mention https://github.com/kipoi/website/issues/78  The Kipoi model list [here](https://kipoi.org/groups/) now uses Manubot to extract author information from the DOI or arXiv links.

This could fit with our new discussion of the v0.2.0 features or at the very end of the Manubot section that discusses current usage.

**Comment by agitter** [comment]
Now that #99 is merged, we could close this.  Or I'll make a proofreading pull request and close this issue with that new pull request.

**Comment by vsmalladi** [comment]
@agitter I think making it a proofreading pull request makes sense.
